### PR TITLE
fix(file transfer widget): QPushButton allows image to overflow

### LINKED ISSUE #3042: [Regression] file transfers widget is too small when images are transferred
Brief description: Images in file transfer widget aren't displayed properly any longer, and they're visible  "outside" of the file transfer widget

Operating System: Gentoo x86_64
qTox version: 252c9c8fae35f0258381537fee444b5eb02a9d7c
Qt: 5.5.1

Reproducible: Always

**Steps to reproduce:**  
1.  Send/receive picture
2.  Look at left corners of the file transfer widget

**Observed Behavior:**  
Visible corners of pictures, file transfer widget is smaller than it is supposed to be.

**Expected Behavior:**  
Corners of pics aren't supposed to be visible, widget shouldn't be that small.

**Additional info:**  
Before regression:
before

Currently:
regression

### PR DESCRIPTION
**Pull request by Talkless**
Regression was due to fact that QPushButton allows icon to overflow.
This patch does:
1. Scale and crop icon to fit into button.
2. Avoid upscaling small images.
3. Refactor FileTransferWidget::showPreview() to load image from file only once.

Fixes #3042 

Screenshot:
https://github.com/tux3/qTox/issues/3042#issuecomment-209565743

### CODE REVIEW

**Comment by ghost** [comment]
Commit message needs more https://github.com/tux3/qTox/blob/master/CONTRIBUTING.md#-git-commit-guidelines

**Comment by Talkless** [comment]
@kehugter could you please be more specific?

**Comment by zetok** [comment]
@Talkless basically commit message should adhere to guidelines, and it would need to be adjusted to something like

```
fix(file transfer widget): QPushButton allows image to overflow

Introduced in 857dfbcd4c1ecdab2b35c5bee8974bdcdef99558

Regression was due to fact that QPushButton allows icon to overflow.
This patch does:
1. Scale and crop icon to fit into button.
2. Avoid upscaling small images.
3. Refactor FileTransferWidget::showPreview() to load image from file
   only once.

Closes #3042
```

**Comment by Talkless** [comment]
Thanks @zetok , that looks better. I'll amend tonight.

File: src/chatlog/content/filetransferwidget.cpp [hunk 1]
```diff
@@ -537,3 +539,29 @@ void FileTransferWidget::onPreviewButtonClicked()
 {
     handleButton(ui->previewButton);
 }
+
+QPixmap FileTransferWidget::scaleCropIntoSquare(const QPixmap &source, const int targetSize) {
```
Comment (zetok) [inline src/chatlog/content/filetransferwidget.cpp]: https://github.com/tux3/qTox/wiki/Coding#coding-style

i.e. should be

```
function()
{
    something;
}
```

~Same goes for the rest of code.

**Comment by Talkless** [comment]
Oh sorry. If's also.. Gonna fix.

**Comment by Talkless** [comment]
I've messed up something with git...

**Comment by Talkless** [comment]
Looks like I've successfully squashed.

**Comment by Talkless** [comment]
Thanks. Sorry for problematic PR though...

**Comment by zetok** [comment]
> Sorry for problematic PR though...

Nah, the PR was great :)

Only recently qTox got the requirement for commit message format, and it was still missing the script to verify it when you've made PR – so it's not a problem.

As for coding style – docs about it were kinda hidden; that should probably be fixed with #3149.
