### PR TITLE
fix(core): correctly relink ui/core when core is changed

### LINKED ISSUE #5710: Reconnect button doesn't reconnect
qTox only goes offline, and never comes back online.

Enable UDP - on
Enable LAN discovery - on
No proxy

version 1.16.3.467 (rev.678fc51c) from a package.
FreeBSD 12

### PR DESCRIPTION
**Pull request by Kribylet**
Widget was only connecting the Core to itself during initialization, but the Core instance could change during a restartCore call. This commit will make Widget link the Core to itself when it changes rather than only on initialization.

Fixes #5710

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5721)

### CODE REVIEW

**Comment by Kribylet** [comment]
Changed to use reference instead of pointer

File: src/widget/widget.cpp [hunk 1]
```diff
@@ -675,6 +675,37 @@ void Widget::onSelfAvatarLoaded(const QPixmap& pic)
     profilePicture->setPixmap(pic);
 }
 
+void Widget::onCoreChanged(Core& core) {
```
Comment (sudden6) [inline src/widget/widget.cpp]: brace should be on the next line, was this formatted by clang-format this way?

**Review by sudden6 — COMMENTED** [review]
lgtm, small mistake found

File: src/widget/widget.cpp (hunk 1 above)
Comment (Kribylet) [reply src/widget/widget.cpp]: It wasn't, I forgot to run format. Fixed.

**Review by sudden6 — APPROVED** [review]
:lgtm_strong:

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/qtox/qtox/5721#-:-LiI7yc92lUpwBlA0Hfh:b-jbsf8z)* status: :shipit: complete! 1 of 1 LGTMs obtained
