### PR TITLE
fix(friendwidget):the limitation of the group's  name in the shortcut menu

### LINKED ISSUE #3201: the problem with displaying long groupchat's names
##### Brief Description

qTox version:  v1.3.0-234-gd0ea5bb.

Reproducible: Always 

if the group is assigned a very long name it is shown wrong in the context menu of contacts.

offer automatically truncate long names in the context menu

### PR DESCRIPTION
**Pull request by PKEv**
close #3201

### CODE REVIEW

**Comment by sudden6** [comment]
Please add a comment that notes what this change does to the code.

File: src/widget/friendwidget.cpp [hunk 1]
```diff
@@ -89,7 +89,13 @@ void FriendWidget::contextMenuEvent(QContextMenuEvent * event)
 
     for (Group* group : GroupList::getAllGroups())
     {
-        QAction* groupAction = inviteMenu->addAction(tr("Invite to group '%1'").arg(group->getGroupWidget()->getName()));
+        int max_name_len = 30;
```
Comment (sudden6) [inline src/widget/friendwidget.cpp]: Our coding style says `camelCase for variables, CamelCase for classes`
