### PR TITLE
fix(widget): Added saving window state before closing

### LINKED ISSUE #3397: qTox not fully stretched after opening hidden window
##### Brief Description

When you click on the qTox icon, the window opens not fully stretched when it was closed stretched (click on Close (X) button). And seems that the "Show" button is working correctly - the window is stretched.

OS: Windows 10  
qTox version: v1.4.0-168-geb743b4.
Commit hash:  eb743b4
Hardware:  ASUS T200TA

Reproducible: Always
##### Steps to reproduce
1. Click on qTox icon.

### PR DESCRIPTION
**Pull request by Diadlo**
It's needed if user setup `Close to tray`
Fix #3397.

### CODE REVIEW

File: src/widget/widget.cpp [hunk 1]
```diff
@@ -411,21 +411,28 @@ void Widget::init()
...
-           {
-                if (ce->oldState() & Qt::WindowMaximized)
-                    wasMaximized = true;
-                else
-                    wasMaximized = false;
-           }
+    QWindowStateChangeEvent *ce = nullptr;
+    Qt::WindowStates state = windowState();
+
+    switch (event->type()) {
```
Comment (sudden6) [inline src/widget/widget.cpp]: `{` coding style

**Comment by DX37** [comment]
It works. Thanks ^^
