### PR TITLE
fix(x11grab): try and use the current display

### LINKED ISSUE #3500: Desktop capture not work with NVIDIA discrete video card
##### Brief Description

OS: Linux Debian 8
qTox version: Nightly
Commit hash:  -
toxcore:   0.0.0
Qt:  5.6.1
Hardware:  Nvidia Quadro k600

Reproducible: Always
##### Steps to reproduce
1. Run qtox.
2. Go to Audio/Video.
3. Set video device : Desktop
##### Observed Behavior

Don't see desktop, only avatar in preview window
and in videocall.
##### Expected Behavior

Want to see desktop in preview window
and in videocall.
##### Additional Info

In debug mode (running from terminal) when
I set desktop as video device, see next information:
[12:11:25.724] src/video/camerasource.cpp:209 : Debug: Opening device  "x11grab#:0"
Invalid MIT-MAGIC-COOKIE-1 key[x11grab @ 0x1c86f80] Cannot open display :0, error 1.
In log file see next information:
[12:04:00.560] src/video/camerasource.cpp:209 : Debug: Opening device  "x11grab#:0"
[12:04:00.562] src/video/camerasource.cpp:225 : Warning: Failed to open device!

my $DISPLAY:
$ echo $DISPLAY
:1

On other computer with integrated video card 
$ echo $DISPLAY
:0.0
And all works.

### PR DESCRIPTION
**Pull request by b4n**
Don't hard-code ":0" as the display and try and use the DISPLAY environment variable instead.

This fixes screen grabbing under X11 when the user is not on screen 0.

Fix #3500.

### CODE REVIEW

**Comment by b4n** [comment]
(BTW, it's not only a theoretical fix for #3500, I had the same problem because my session runs as `:1` and then the x11grab source wouldn't work.  This patches fixes it)

File: src/video/cameradevice.cpp [hunk 1]
```diff
@@ -317,7 +317,17 @@ QVector<QPair<QString, QString>> CameraDevice::getDeviceList()
...
         if (idesktopFormat->name == QString("x11grab"))
-            devices.push_back(QPair<QString,QString>{"x11grab#:0", QObject::tr("Desktop", "Desktop as a camera input for screen sharing")});
+        {
+            QString dev = "x11grab#";
+            QByteArray display = qgetenv("DISPLAY");
+
+            if (display.isNull())
+                dev += ":0";
+            else
+                dev += display.constData();
```
Comment (antis81) [inline src/video/cameradevice.cpp:327]: Aren't you missing a colon here?

Comment (b4n) [inline src/video/cameradevice.cpp:327]: unless `$DISPLAY` is malformed, no.

``` console
$ echo $DISPLAY
:1.0
```

As with what we want here, it's `[host]:display[.screen]`.  See https://tronche.com/gui/x/xlib/display/opening.html

Comment (antis81) [inline src/video/cameradevice.cpp:327]: Ok then. Nevermind.

**Comment by agilob** [comment]
https://github.com/tux3/qTox/issues/518

**Comment by b4n** [comment]
@agilob ?  I'm not too knowledgeable, but I don't think it's related, as AFAIK the DISPLAY cannot change inside an X session at all.
Screen too AFAIK, as it's _not_ a monitor but here talks about X screens (groups of devices).  Which virtually nobody uses nowadays and unfortunately desktop start to drop support for.

It's also unrelated to the new setting "Screen" in the preferences, that IIUC just selects the area of the Nth monitor, so it should work fine.  But admittedly I can't test that feature as I don't have a second monitor to plug right now.
