### PR TITLE
fix(widget): Fix double free crash on group leave

### LINKED ISSUE #5004: [Urgent] Crash on group leave, 100% of time on 1.14
##### Brief Description

OS: Ubuntu 16.04
qTox version: v1.14.0
Commit hash:  b6e811ca3ad6bad9f7d64150c5c122e35a0d7bee
toxcore:  0.2.1
Qt:  5.5.1
Hardware:  Desktop, high resources

Reproducible: Always

##### Steps to reproduce

1. Create group
2. Leave group

##### Observed Behavior
...

##### Expected Behavior
qTox crash, double free

##### Additional Info

```
[22:22:41.188 UTC] core/core.cpp:570 : Debug: "Group 0, Peer 1, name changed to tox-user"
[22:22:41.188 UTC] core/core.cpp:562 : Debug: "Group 0 peerlist changed"
[22:22:41.188 UTC] core/core.cpp:1087 : Critical: Peer not found
[22:22:41.206 UTC] core/coreav.cpp:582 : Debug: "Leaving group call 0"
[22:22:41.210 UTC] core/coreav.cpp:582 : Debug: "Leaving group call 0"
[22:22:41.212 UTC] core/coreav.cpp:582 : Debug: "Leaving group call 0"
[22:22:41.214 UTC] core/coreav.cpp:582 : Debug: "Leaving group call 0"
[22:22:41.216 UTC] core/coreav.cpp:582 : Debug: "Leaving group call 0"
[22:22:42.288 UTC] core/core.cpp:570 : Debug: "Group 0, Peer 2, name changed to Anthony"
[22:22:42.291 UTC] core/coreav.cpp:582 : Debug: "Leaving group call 0"
[22:22:47.112 UTC] core/coreav.cpp:582 : Debug: "Leaving group call 0"
*** Error in `./qtox': double free or corruption (out): 0x00007ffc235b6780 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f9a4eb1b7e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f9a4eb2437a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7f9a4eb2853c]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN14QObjectPrivate14deleteChildrenEv+0x5b)[0x7f9a4f4a328b]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN7QWidgetD1Ev+0x358)[0x7f9a54f58708]
./qtox(_ZN21GenericChatItemWidgetD1Ev+0x5f)[0x6a8451]
./qtox(_ZN21GenericChatroomWidgetD1Ev+0x4f)[0x6a8525]
./qtox(_ZN11GroupWidgetD1Ev+0x5b)[0x7c678f]
./qtox(_ZN11GroupWidgetD0Ev+0x27)[0x7c67eb]
./qtox(_ZN6Widget11removeGroupEP5Groupb+0x135)[0x66a84d]
./qtox(_ZN6Widget11removeGroupEi+0x3f)[0x66a98d]
./qtox[0x69fa4d]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN11QMetaObject8activateEP7QObjectiiPPv+0x7ea)[0x7f9a4f4a4d2a]
./qtox(_ZN11GroupWidget11removeGroupEi+0x55)[0x69a88d]
./qtox(_ZN11GroupWidget16contextMenuEventEP17QContextMenuEvent+0x2fd)[0x7c6bcf]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN7QWidget5eventEP6QEvent+0x668)[0x7f9a54f5cfc8]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN6QFrame5eventEP6QEvent+0x1e)[0x7f9a5505bb8e]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x8c)[0x7f9a54f1a05c]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0xd0c)[0x7f9a54f1ffcc]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication14notifyInternalEP7QObjectP6QEvent+0xdb)[0x7f9a4f47638b]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x1b86f2)[0x7f9a54f776f2]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(+0x1bab7b)[0x7f9a54f79b7b]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x8c)[0x7f9a54f1a05c]
/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x256)[0x7f9a54f1f516]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication14notifyInternalEP7QObjectP6QEvent+0xdb)[0x7f9a4f47638b]
/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE+0x281)[0x7f9a4f7b84e1]
/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZN22QGuiApplicationPrivate24processWindowSystemEventEPN29QWindowSystemInterfacePrivate17WindowSystemEventE+0x135)[0x7f9a4f7ba1a5]
/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5(_ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x28)[0x7f9a4f79df08]
/usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5(+0x6b200)[0x7f9a34613200]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_dispatch+0x2a7)[0x7f9a50e40197]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(+0x4a3f0)[0x7f9a50e403f0]
/lib/x86_64-linux-gnu/libglib-2.0.so.0(g_main_context_iteration+0x2c)[0x7f9a50e4049c]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x5f)[0x7f9a4f4cc7cf]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0x10a)[0x7f9a4f473b4a]
/usr/lib/x86_64-linux-gnu/libQt5Core.so.5(_ZN16QCoreApplication4execEv+0x9c)[0x7f9a4f47bbec]
./qtox(main+0x1a59)[0x5f573a]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7f9a4eac4830]
./qtox(_start+0x29)[0x5f2d49]
======= Memory map: ========
00400000-00d18000 r-xp 00000000 fc:01 31859306                           /home/abilinski/build/qTox/qtox
00f18000-00f29000 r--p 00918000 fc:01 31859306                           /home/abilinski/build/qTox/qtox
00f29000-00f2a000 rw-p 00929000 fc:01 31859306                           /home/abilinski/build/qTox/qtox
0223f000-07168000 rw-p 00000000 00:00 0                                  [heap]
7f99f8000000-7f99f8070000 rw-p 00000000 00:00 0
7f99f8070000-7f99fc000000 ---p 00000000 00:00 0
7f99ff7fd000-7f99ff7fe000 ---p 00000000 00:00 0
7f99ff7fe000-7f99ffffe000 rw-p 00000000 00:00 0
7f99ffffe000-7f9a03fff000 rw-s 00000000 00:15 10                         /dev/shm/pulse-shm-2432819051
7f9a03fff000-7f9a08000000 rw-s 00000000 00:15 20                         /dev/shm/pulse-shm-2028987638
7f9a08000000-7f9a08002000 rw-p 00000000 00:00 0
7f9a08002000-7f9a08003000 rw-p 00000000 00:00 0
7f9a08003000-7f9a08014000 rw-p 00000000 00:00 0
7f9a08014000-7f9a08017000 rw-p 00000000 00:00 0
7f9a08017000-7f9a08018000 rw-p 00000000 00:00 0
7f9a08018000-7f9a08019000 rw-p 00000000 00:00 0
7f9a08019000-7f9a0836f000 rw-p 00000000 00:00 0
7f9a0836f000-7f9a0c000000 ---p 00000000 00:00 0
7f9a0c000000-7f9a0c021000 rw-p 00000000 00:00 0
7f9a0c021000-7f9a10000000 ---p 00000000 00:00 0
7f9a10000000-7f9a103bd000 rw-p 00000000 00:00 0
7f9a103bd000-7f9a14000000 ---p 00000000 00:00 0
7f9a14000000-7f9a14021000 rw-p 00000000 00:00 0
7f9a14021000-7f9a18000000 ---p 00000000 00:00 0
7f9a18000000-7f9a18179000 rw-p 00000000 00:00 0
7f9a18179000-7f9a1c000000 ---p 00000000 00:00 0
7f9a1c000000-7f9a1c021000 rw-p 00000000 00:00 0
7f9a1c021000-7f9a20000000 ---p 00000000 00:00 0
7f9a20688000-7f9a2096b000 r--p 00000000 fc:01 2754055                    /usr/share/fonts/truetype/ancient-scripts/Symbola_hint.ttf
7f9a2096e000-7f9a20b44000 rw-s 00000000 00:05 293208083                  /SYSV00000000 (deleted)
7f9a20b44000-7f9a20b45000 ---p 00000000 00:00 0
7f9a20b45000-7f9a20c45000 rw-p 00000000 00:00 0
7f9a20e1a000-7f9a21ffc000 r--p 00000000 fc:01 2753997                    /usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc
7f9a21ffc000-7f9a21ffd000 ---p 00000000 00:00 0
7f9a21ffd000-7f9a227fd000 rw-p 00000000 00:00 0
7f9a227fd000-7f9a227fe000 ---p 00000000 00:00 0
7f9a227fe000-7f9a22ffe000 rw-p 00000000 00:00 0
7f9a22ffe000-7f9a22fff000 ---p 00000000 00:00 0
7f9a22fff000-7f9a237ff000 rw-p 00000000 00:00 0
7f9a237ff000-7f9a23800000 ---p 00000000 00:00 0
7f9a23800000-7f9a24000000 rw-p 00000000 00:00 0
7f9a24000000-7f9a24028000 rw-p 00000000 00:00 0
7f9a24028000-7f9a28000000 ---p 00000000 00:00 0
7f9a28000000-7f9a28021000 rw-p 00000000 00:00 0
7f9a28021000-7f9a2c000000 ---p 00000000 00:00 0
7f9a2c000000-7f9a2c021000 rw-p 00000000 00:00 0
7f9a2c021000-7f9a30000000 ---p 00000000 00:00 0
7f9a300b6000-7f9a300bd000 r--s 00000000 fc:01 1839076                    /usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache
7f9a300f5000-7f9a30110000 r--p 00000000 fc:01 2754098                    /usr/share/fonts/truetype/liberation/LiberationMono-Regular.ttf
7f9a30118000-7f9a30148000 rwxp 00000000 00:00 0
7f9a30150000-7f9a301a2000 r--p 00000000 fc:01 2754186                    /usr/share/fonts/truetype/ubuntu-font-family/Ubuntu-B.ttf
7f9a301b2000-7f9a30209000 r--p 00000000 fc:01 2754193                    /usr/share/fonts/truetype/ubuntu-font-family/Ubuntu-R.ttf
7f9a30209000-7f9a3020a000 ---p 00000000 00:00 0
7f9a3020a000-7f9a30a0a000 rw-p 00000000 00:00 0
7f9a30a0a000-7f9a30a0b000 ---p 00000000 00:00 0
7f9a30a0b000-7f9a3120b000 rw-p 00000000 00:00 0
7f9a3120b000-7f9a31262000 r-xp 00000000 fc:01 1581433                    /usr/lib/x86_64-linux-gnu/libjpeg.so.8.0.2
7f9a31262000-7f9a31462000 ---p 00057000 fc:01 1581433                    /usr/lib/x86_64-linux-gnu/libjpeg.so.8.0.2
7f9a31462000-7f9a31463000 r--p 00057000 fc:01 1581433                    /usr/lib/x86_64-linux-gnu/libjpeg.so.8.0.2
7f9a31463000-7f9a31464000 rw-p 00058000 fc:01 1581433                    /usr/lib/x86_64-linux-gnu/libjpeg.so.8.0.2
7f9a3148e000-7f9a31498000 r-xp 00000000 fc:01 1989111                    /usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqjpeg.so
7f9a31498000-7f9a31499000 r--p 00009000 fc:01 1989111                    /usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqjpeg.so
7f9a31499000-7f9a3149a000 rw-p 0000a000 fc:01 1989111                    /usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqjpeg.so
7f9a3149a000-7f9a314a0000 r-xp 00000000 fc:01 1989113                    /usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqico.so
7f9a314a0000-7f9a314a1000 ---p 00006000 fc:01 1989113                    /usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqico.so
7f9a314a1000-7f9a314a2000 r--p 00006000 fc:01 1989113                    /usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqico.so
7f9a314a2000-7f9a314a3000 rw-p 00007000 fc:01 1989113                    /usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqico.so
7f9a314a3000-7f9a314a9000 r-xp 00000000 fc:01 1989112                    /usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqgif.so
7f9a314a9000-7f9a314aa000 r--p 00005000 fc:01 1989112                    /usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqgif.so
7f9a314aa000-7f9a314ab000 rw-p 00006000 fc:01 1989112                    /usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqgif.so
7f9a314ad000-7f9a314c1000 rw-s 00000000 00:05 293699639                  /SYSV00000000 (deleted)
7f9a314c1000-7f9a314fc000 rw-s 00000000 00:05 293240890                  /SYSV00000000 (deleted)
7f9a314fc000-7f9a315a8000 r--p 00000000 fc:01 2754058                    /usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf
7f9a315a8000-7f9a315ad000 r-xp 00000000 fc:01 1968801                    /usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqsvg.so
7f9a315ad000-7f9a315ae000 r--p 00004000 fc:01 1968801                    /usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqsvg.so
7f9a315ae000-7f9a315af000 rw-p 00005000 fc:01 1968801                    /usr/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqsvg.so
7f9a315af000-7f9a315b8000 r-xp 00000000 fc:01 1968797                    /usr/lib/x86_64-linux-gnu/qt5/plugins/iconengines/libqsvgicon.so
7f9a315b8000-7f9a315b9000 r--p 00008000 fc:01 1968797                    /usr/lib/x86_64-linux-gnu/qt5/plugins/iconengines/libqsvgicon.so
7f9a315b9000-7f9a315ba000 rw-p 00009000 fc:01 1968797                    /usr/lib/x86_64-linux-gnu/qt5/plugins/iconengines/libqsvgicon.so
7f9a315ba000-7f9a315bc000 rw-s 00000000 00:05 288653319                  /SYSV510126c2 (deleted)
7f9a315c4000-7f9a315c5000 ---p 00000000 00:00 0
7f9a315c5000-7f9a31dc5000 rw-p 00000000 00:00 0
7f9a31dc5000-7f9a31dd0000 r--s 00000000 fc:01 26740213                   /var/cache/fontconfig/945677eb7aeaf62f1d50efc3fb3ec7d8-le64.cache-6
7f9a31dd0000-7f9a31dd2000 r--s 00000000 fc:01 26755382                   /var/cache/fontconfig/99e8ed0e538f840c565b6ed5dad60d56-le64.cache-6
7f9a31dd2000-7f9a31dd8000 r--s 00000000 fc:01 26746950                   /var/cache/fontconfig/2cd17615ca594fa2959ae173292e504c-le64.cache-6
7f9a31dd8000-7f9a31dd9000 r--s 00000000 fc:01 26746949                   /var/cache/fontconfig/0d8c3b2ac0904cb8a57a757ad11a4a08-le64.cache-6
7f9a31dd9000-7f9a31ddd000 r--s 00000000 fc:01 26743480                   /var/cache/fontconfig/de156ccd2eddbdc19d37a45b8b2aac9c-le64.cache-6
7f9a31ddd000-7f9a31df2000 r--s 00000000 fc:01 26746834                   /var/cache/fontconfig/04aabc0a78ac019cf9454389977116d2-le64.cache-6
7f9a31df2000-7f9a31df3000 r--s 00000000 fc:01 26746833                   /var/cache/fontconfig/1ac9eb803944fde146138c791f5cc56a-le64.cache-6
7f9a31df3000-7f9a31df7000 r--s 00000000 fc:01 26746832                   /var/cache/fontconfig/385c0604a188198f04d133e54aba7fe7-le64.cache-6
7f9a31df7000-7f9a31df8000 r--s 00000000 fc:01 26746831                   /var/cache/fontconfig/dc05db6664285cc2f12bf69c139ae4c3-le64.cache-6
7f9a31df8000-7f9a31dfb000 r--s 00000000 fc:01 26746830                   /var/cache/fontconfig/767a8244fc0220cfb567a839d0392e0b-le64.cache-6
7f9a31dfb000-7f9a31e00000 r--s 00000000 fc:01 26746828                   /var/cache/fontconfig/8801497958630a81b71ace7c5f9b32a8-le64.cache-6
7f9a31e00000-7f9a31e04000 r--s 00000000 fc:01 26743433                   /var/cache/fontconfig/c57959a16110560c8d0fcea73374aeeb-le64.cache-6
7f9a31e04000-7f9a31e0b000 r--s 00000000 fc:01 26746807                   /var/cache/fontconfig/3047814df9a2f067bd2d96a2b9c36e5a-le64.cache-6
7f9a31e0b000-7f9a31e11000 r--s 00000000 fc:01 26746676                   /var/cache/fontconfig/b47c4e1ecd0709278f4910c18777a504-le64.cache-6
7f9a31e11000-7f9a31e24000 r--s 00000000 fc:01 26746675                   /var/cache/fontconfig/d52a8644073d54c13679302ca1180695-le64.cache-6
7f9a31e24000-7f9a31e2f000 r--s 00000000 fc:01 26745554                   /var/cache/fontconfig/d589a48862398ed80a3d6066f4f56f4c-le64.cache-6
7f9a31e2f000-7f9a31e46000 r-xp 00000000 fc:01 1582049                    /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0.0.0
7f9a31e46000-7f9a32045000 ---p 00017000 fc:01 1582049                    /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0.0.0
7f9a32045000-7f9a32047000 r--p 00016000 fc:01 1582049                    /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0.0.0
7f9a32047000-7f9a32048000 rw-p 00018000 fc:01 1582049                    /usr/lib/x86_64-linux-gnu/libxcb-glx.so.0.0.0
7f9a32048000-7f9a32053000 r--s 00000000 fc:01 26746588                   /var/cache/fontconfig/83bf95040141907cd45bb53cf7c1c148-le64.cache-6
7f9a32053000-7f9a32065000 r--s 00000000 fc:01 26738774                   /var/cache/fontconfig/9b89f8e3dae116d678bbf48e5f21f69b-le64.cache-6
7f9a32065000-7f9a32072000 r--s 00000000 fc:01 26748589                   /var/cache/fontconfig/e13b20fdb08344e0e664864cc2ede53d-le64.cache-6
7f9a32072000-7f9a32073000 ---p 00000000 00:00 0
7f9a32073000-7f9a32873000 rw-p 00000000 00:00 0
7f9a32873000-7f9a32878000 r-xp 00000000 fc:01 1582071                    /usr/lib/x86_64-linux-gnu/libxcb-util.so.1.0.0
7f9a32878000-7f9a32a77000 ---p 00005000 fc:01 1582071                    /usr/lib/x86_64-linux-gnu/libxcb-util.so.1.0.0
7f9a32a77000-7f9a32a78000 r--p 00004000 fc:01 1582071                    /usr/lib/x86_64-linux-gnu/libxcb-util.so.1.0.0
7f9a32a78000-7f9a32a79000 rw-p 00005000 fc:01 1582071                    /usr/lib/x86_64-linux-gnu/libxcb-util.so.1.0.0
7f9a32a79000-7f9a32a7d000 r-xp 00000000 fc:01 31720689                   /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7f9a32a7d000-7f9a32c7c000 ---p 00004000 fc:01 31720689                   /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7f9a32c7c000-7f9a32c7d000 r--p 00003000 fc:01 31720689                   /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7f9a32c7d000-7f9a32c7e000 rw-p 00004000 fc:01 31720689                   /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7f9a32c7e000-7f9a32cf8000 r-xp 00000000 fc:01 1579427                    /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5.5.1
7f9a32cf8000-7f9a32cf9000 ---p 0007a000 fc:01 1579427                    /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5.5.1
7f9a32cf9000-7f9a32cfa000 r--p 0007a000 fc:01 1579427                    /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5.5.1
7f9a32cfa000-7f9a32cfb000 rw-p 0007b000 fc:01 1579427                    /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5.5.1
7f9a32cfb000-7f9a32cfc000 rw-p 00000000 00:00 0
7f9a32cfc000-7f9a32d39000 r-xp 00000000 fc:01 1582081                    /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0.0.0
7f9a32d39000-7f9a32f38000 ---p 0003d000 fc:01 1582081                    /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0.0.0
7f9a32f38000-7f9a32f3a000 r--p 0003c000 fc:01 1582081                    /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0.0.0
7f9a32f3a000-7f9a32f3b000 rw-p 0003e000 fc:01 1582081                    /usr/lib/x86_64-linux-gnu/libxkbcommon.so.0.0.0
7f9a32f3b000-7f9a32f42000 r-xp 00000000 fc:01 1582079                    /usr/lib/x86_64-linux-gnu/libxkbcommon-x11.so.0.0.0
7f9a32f42000-7f9a33141000 ---p 00007000 fc:01 1582079                    /usr/lib/x86_64-linux-gnu/libxkbcommon-x11.so.0.0.0
7f9a33141000-7f9a33142000 r--p 00006000 fc:01 1582079                    /usr/lib/x86_64-linux-gnu/libxkbcommon-x11.so.0.0.0
7f9a33142000-7f9a33143000 rw-p 00007000 fc:01 1582079                    /usr/lib/x86_64-linux-gnu/libxkbcommon-x11.so.0.0.0
7f9a33143000-7f9a3315d000 r-xp 00000000 fc:01 1582075                    /usr/lib/x86_64-linux-gnu/libxcb-xkb.so.1.0.0
7f9a3315d000-7f9a3335c000 ---p 0001a000 fc:01 1582075                    /usr/lib/x86_64-linux-gnu/libxcb-xkb.so.1.0.0
7f9a3335c000-7f9a3335d000 r--p 00019000 fc:01 1582075                    /usr/lib/x86_64-linux-gnu/libxcb-xkb.so.1.0.0
7f9a3335d000-7f9a3335e000 rw-p 0001a000 fc:01 1582075                    /usr/lib/x86_64-linux-gnu/libxcb-xkb.so.1.0.0
7f9a3335e000-7f9a33360000 r-xp 00000000 fc:01 1582055                    /usr/lib/x86_64-linux-gnu/libxcb-keysyms.so.1.0.0
7f9a33360000-7f9a3355f000 ---p 00002000 fc:01 1582055                    /usr/lib/x86_64-linux-gnu/libxcb-keysyms.so.1.0.0
7f9a3355f000-7f9a33560000 r--p 00001000 fc:01 1582055                    /usr/lib/x86_64-linux-gnu/libxcb-keysyms.so.1.0.0
7f9a33560000-7f9a33561000 rw-p 00002000 fc:01 1582055                    /usr/lib/x86_64-linux-gnu/libxcb-keysyms.so.1.0.0
7f9a33561000-7f9a3356d000 r-xp 00000000 fc:01 1582059                    /usr/lib/x86_64-linux-gnu/libxcb-randr.so.0.1.0
7f9a3356d000-7f9a3376d000 ---p 0000c000 fc:01 1582059                    /usr/lib/x86_64-linux-gnu/libxcb-randr.so.0.1.0
7f9a3376d000-7f9a3376e000 r--p 0000c000 fc:01 1582059                    /usr/lib/x86_64-linux-gnu/libxcb-randr.so.0.1.0
7f9a3376e000-7f9a3376f000 rw-p 0000d000 fc:01 1582059                    /usr/lib/x86_64-linux-gnu/libxcb-randr.so.0.1.0
7f9a3376f000-7f9a33774000 r-xp 00000000 fc:01 1582069                    /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1.0.0
7f9a33774000-7f9a33974000 ---p 00005000 fc:01 1582069                    /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1.0.0
7f9a33974000-7f9a33975000 r--p 00005000 fc:01 1582069                    /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1.0.0
7f9a33975000-7f9a33976000 rw-p 00006000 fc:01 1582069                    /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1.0.0
7f9a33976000-7f9a3397a000 r-xp 00000000 fc:01 1582051                    /usr/lib/x86_64-linux-gnu/libxcb-icccm.so.4.0.0
7f9a3397a000-7f9a33b79000 ---p 00004000 fc:01 1582051                    /usr/lib/x86_64-linux-gnu/libxcb-icccm.so.4.0.0
7f9a33b79000-7f9a33b7a000 r--p 00003000 fc:01 1582051                    /usr/lib/x86_64-linux-gnu/libxcb-icccm.so.4.0.0
7f9a33b7a000-7f9a33b7b000 rw-p 00004000 fc:01 1582051                    /usr/lib/x86_64-linux-gnu/libxcb-icccm.so.4.0.0
7f9a33b7b000-7f9a33b7f000 r-xp 00000000 fc:01 1582053                    /usr/lib/x86_64-linux-gnu/libxcb-image.so.0.0.0
7f9a33b7f000-7f9a33d7e000 ---p 00004000 fc:01 1582053                    /usr/lib/x86_64-linux-gnu/libxcb-image.so.0.0.0
7f9a33d7e000-7f9a33d7f000 r--p 00003000 fc:01 1582053                    /usr/lib/x86_64-linux-gnu/libxcb-image.so.0.0.0
7f9a33d7f000-7f9a33d80000 rw-p 00004000 fc:01 1582053                    /usr/lib/x86_64-linux-gnu/libxcb-image.so.0.0.0
7f9a33d80000-7f9a33d96000 r-xp 00000000 fc:01 1580565                    /usr/lib/x86_64-linux-gnu/libICE.so.6.3.0
7f9a33d96000-7f9a33f95000 ---p 00016000 fc:01 1580565                    /usr/lib/x86_64-linux-gnu/libICE.so.6.3.0
7f9a33f95000-7f9a33f96000 r--p 00015000 fc:01 1580565                    /usr/lib/x86_64-linux-gnu/libICE.so.6.3.0
7f9a33f96000-7f9a33f97000 rw-p 00016000 fc:01 1580565                    /usr/lib/x86_64-linux-gnu/libICE.so.6.3.0
7f9a33f97000-7f9a33f9a000 rw-p 00000000 00:00 0
7f9a33f9a000-7f9a33fa1000 r-xp 00000000 fc:01 1580685                    /usr/lib/x86_64-linux-gnu/libSM.so.6.0.1
7f9a33fa1000-7f9a341a0000 ---p 00007000 fc:01 1580685                    /usr/lib/x86_64-linux-gnu/libSM.so.6.0.1
7f9a341a0000-7f9a341a1000 r--p 00006000 fc:01 1580685                    /usr/lib/x86_64-linux-gnu/libSM.so.6.0.1
7f9a341a1000-7f9a341a2000 rw-p 00007000 fc:01 1580685                    /usr/lib/x86_64-linux-gnu/libSM.so.6.0.1
7f9a341a2000-7f9a341a5000 r-xp 00000000 fc:01 1582061                    /usr/lib/x86_64-linux-gnu/libxcb-render-util.so.0.0.0
7f9a341a5000-7f9a343a4000 ---p 00003000 fc:01 1582061                    /usr/lib/x86_64-linux-gnu/libxcb-render-util.so.0.0.0
7f9a343a4000-7f9a343a5000 r--p 00002000 fc:01 1582061                    /usr/lib/x86_64-linux-gnu/libxcb-render-util.so.0.0.0
7f9a343a5000-7f9a343a6000 rw-p 00003000 fc:01 1582061                    /usr/lib/x86_64-linux-gnu/libxcb-render-util.so.0.0.0
7f9a343a6000-7f9a343a7000 r-xp 00000000 fc:01 1580693                    /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1.0.0
7f9a343a7000-7f9a345a6000 ---p 00001000 fc:01 1580693                    /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1.0.0
7f9a345a6000-7f9a345a7000 r--p 00000000 fc:01 1580693                    /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1.0.0
7f9a345a7000-7f9a345a8000 rw-p 00001000 fc:01 1580693                    /usr/lib/x86_64-linux-gnu/libX11-xcb.so.1.0.0
7f9a345a8000-7f9a34688000 r-xp 00000000 fc:01 1579445                    /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5.5.1
7f9a34688000-7f9a34689000 ---p 000e0000 fc:01 1579445                    /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5.5.1
7f9a34689000-7f9a3468d000 r--p 000e0000 fc:01 1579445                    /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5.5.1
7f9a3468d000-7f9a34691000 rw-p 000e4000 fc:01 1579445                    /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5.5.1
7f9a34691000-7f9a34692000 r--s 00000000 fc:01 26752829                   /var/cache/fontconfig/4794a0821666d79190d59a36cb4f44b5-le64.cache-6
7f9a34692000-7f9a34693000 r--s 00000000 fc:01 26746808                   /var/cache/fontconfig/bab58bb527bb656aaa9f116d68a48d89-le64.cache-6
7f9a34693000-7f9a34694000 r--s 00000000 fc:01 26746723                   /var/cache/fontconfig/56cf4f4769d0f4abc89a4895d7bd3ae1-le64.cache-6
7f9a34694000-7f9a34695000 r--s 00000000 fc:01 26746721                   /var/cache/fontconfig/b9d506c9ac06c20b433354fa67a72993-le64.cache-6
7f9a34695000-7f9a34696000 r--s 00000000 fc:01 26746640                   /var/cache/fontconfig/551ecf3b0e8b0bca0f25c0944f561853-le64.cache-6
7f9a34696000-7f9a34697000 r--s 00000000 fc:01 26746592                   /var/cache/fontconfig/30829fa25452a46451e813d634d7f916-le64.cache-6
7f9a34697000-7f9a34698000 r--s 00000000 fc:01 26746591                   /var/cache/fontconfig/0c9eb80ebd1c36541ebe2852d3bb0c49-le64.cache-6
7f9a34698000-7f9a3469b000 r--s 00000000 fc:01 26746589                   /var/cache/fontconfig/75114ca45c98e8a441da0ff356701271-le64.cache-6
7f9a3469b000-7f9a3469d000 r--s 00000000 fc:01 26753730                   /var/cache/fontconfig/62f91419b9ebdb6975e7e41ab6412357-le64.cache-6
7f9a3469d000-7f9a346a1000 r--s 00000000 fc:01 26751201                   /var/cache/fontconfig/7ef2298fde41cc6eeb7af42e48b7d293-le64.cache-6
7f9a346a9000-7f9a346b8000 r-xp 00000000 fc:01 1989115                    /usr/lib/x86_64-linux-gnu/qt5/plugins/xcbglintegrations/libqxcb-glx-integration.so
7f9a346b8000-7f9a346b9000 ---p 0000f000 fc:01 1989115                    /usr/lib/x86_64-linux-gnu/qt5/plugins/xcbglintegrations/libqxcb-glx-integration.so
7f9a346b9000-7f9a346ba000 r--p 0000f000 fc:01 1989115                    /usr/lib/x86_64-linux-gnu/qt5/plugins/xcbglintegrations/libqxcb-glx-integration.so
7f9a346ba000-7f9a346bb000 rw-p 00010000 fc:01 1989115                    /usr/lib/x86_64-linux-gnu/qt5/plugins/xcbglintegrations/libqxcb-glx-integration.so
7f9a346bb000-7f9a34993000 r--p 00000000 fc:01 1573759                    /usr/lib/locale/locale-archive
7f9a34993000-7f9a349a6000 rw-p 00000000 00:00 0
7f9a349a6000-7f9a349a9000 r-xp 00000000 fc:01 31723881                   /lib/x86_64-linux-gnu/libkeyutils.so.1.5
7f9a349a9000-7f9a34ba8000 ---p 00003000 fc:01 31723881                   /lib/x86_64-linux-gnu/libkeyutils.so.1.5
7f9a34ba8000-7f9a34ba9000 r--p 00002000 fc:01 31723881                   /lib/x86_64-linux-gnu/libkeyutils.so.1.5
7f9a34ba9000-7f9a34baa000 rw-p 00003000 fc:01 31723881                   /lib/x86_64-linux-gnu/libkeyutils.so.1.5
7f9a34baa000-7f9a34c1d000 r-xp 00000000 fc:01 1580551                    /usr/lib/x86_64-linux-gnu/libFLAC.so.8.3.0
7f9a34c1d000-7f9a34e1d000 ---p 00073000 fc:01 1580551                    /usr/lib/x86_64-linux-gnu/libFLAC.so.8.3.0
7f9a34e1d000-7f9a34e1e000 r--p 00073000 fc:01 1580551                    /usr/lib/x86_64-linux-gnu/libFLAC.so.8.3.0
7f9a34e1e000-7f9a34e1f000 rw-p 00074000 fc:01 1580551                    /usr/lib/x86_64-linux-gnu/libFLAC.so.8.3.0
7f9a34e1f000-7f9a34e20000 rw-p 00000000 00:00 0
7f9a34e20000-7f9a34e36000 r-xp 00000000 fc:01 31748877                   /lib/x86_64-linux-gnu/libnsl-2.23.so
7f9a34e36000-7f9a35035000 ---p 00016000 fc:01 31748877                   /lib/x86_64-linux-gnu/libnsl-2.23.so
7f9a35035000-7f9a35036000 r--p 00015000 fc:01 31748877                   /lib/x86_64-linux-gnu/libnsl-2.23.so
7f9a35036000-7f9a35037000 rw-p 00016000 fc:01 31748877                   /lib/x86_64-linux-gnu/libnsl-2.23.so
7f9a35037000-7f9a35039000 rw-p 00000000 00:00 0
7f9a35039000-7f9a3503f000 r-xp 00000000 fc:01 1580953                    /usr/lib/x86_64-linux-gnu/libdatrie.so.1.3.3
7f9a3503f000-7f9a3523f000 ---p 00006000 fc:01 1580953                    /usr/lib/x86_64-linux-gnu/libdatrie.so.1.3.3
7f9a3523f000-7f9a35240000 r--p 00006000 fc:01 1580953                    /usr/lib/x86_64-linux-gnu/libdatrie.so.1.3.3
7f9a35240000-7f9a35241000 rw-p 00007000 fc:01 1580953                    /usr/lib/x86_64-linux-gnu/libdatrie.so.1.3.3
7f9a35241000-7f9a35242000 rw-p 00000000 00:00 0
7f9a35242000-7f9a3524c000 r-xp 00000000 fc:01 1573370                    /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
7f9a3524c000-7f9a3544b000 ---p 0000a000 fc:01 1573370                    /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
7f9a3544b000-7f9a3544c000 r--p 00009000 fc:01 1573370                    /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
7f9a3544c000-7f9a3544d000 rw-p 0000a000 fc:01 1573370                    /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
7f9a3544d000-7f9a35450000 r-xp 00000000 fc:01 31723829                   /lib/x86_64-linux-gnu/libcom_err.so.2.1
7f9a35450000-7f9a3564f000 ---p 00003000 fc:01 31723829                   /lib/x86_64-linux-gnu/libcom_err.so.2.1
7f9a3564f000-7f9a35650000 r--p 00002000 fc:01 31723829                   /lib/x86_64-linux-gnu/libcom_err.so.2.1
7f9a35650000-7f9a35651000 rw-p 00003000 fc:01 31723829                   /lib/x86_64-linux-gnu/libcom_err.so.2.1
7f9a35651000-7f9a35652000 rw-p 00000000 00:00 0
7f9a35652000-7f9a3567e000 r-xp 00000000 fc:01 1573364                    /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
7f9a3567e000-7f9a3587d000 ---p 0002c000 fc:01 1573364                    /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
7f9a3587d000-7f9a3587f000 r--p 0002b000 fc:01 1573364                    /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
7f9a3587f000-7f9a35880000 rw-p 0002d000 fc:01 1573364                    /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
7f9a35880000-7f9a35881000 rw-p 00000000 00:00 0
7f9a35881000-7f9a35944000 r-xp 00000000 fc:01 1573368                    /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
7f9a35944000-7f9a35b44000 ---p 000c3000 fc:01 1573368                    /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
7f9a35b44000-7f9a35b51000 r--p 000c3000 fc:01 1573368                    /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
7f9a35b51000-7f9a35b53000 rw-p 000d0000 fc:01 1573368                    /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
7f9a35b53000-7f9a35b65000 r-xp 00000000 fc:01 31723864                   /lib/x86_64-linux-gnu/libgpg-error.so.0.17.0
7f9a35b65000-7f9a35d65000 ---p 00012000 fc:01 31723864                   /lib/x86_64-linux-gnu/libgpg-error.so.0.17.0
7f9a35d65000-7f9a35d66000 r--p 00012000 fc:01 31723864                   /lib/x86_64-linux-gnu/libgpg-error.so.0.17.0
7f9a35d66000-7f9a35d67000 rw-p 00013000 fc:01 31723864                   /lib/x86_64-linux-gnu/libgpg-error.so.0.17.0
7f9a35d67000-7f9a35d68000 rw-p 00000000 00:00 0
7f9a35d68000-7f9a35d6d000 r-xp 00000000 fc:01 1580801                    /usr/lib/x86_64-linux-gnu/libasyncns.so.0.3.1
7f9a35d6d000-7f9a35f6c000 ---p 00005000 fc:01 1580801                    /usr/lib/x86_64-linux-gnu/libasyncns.so.0.3.1
7f9a35f6c000-7f9a35f6d000 r--p 00004000 fc:01 1580801                    /usr/lib/x86_64-linux-gnu/libasyncns.so.0.3.1
7f9a35f6d000-7f9a35f6e000 rw-p 00005000 fc:01 1580801                    /usr/lib/x86_64-linux-gnu/libasyncns.so.0.3.1
7f9a35f6e000-7f9a35fd0000 r-xp 00000000 fc:01 1579542                    /usr/lib/x86_64-linux-gnu/libsndfile.so.1.0.25
7f9a35fd0000-7f9a361d0000 ---p 00062000 fc:01 1579542                    /usr/lib/x86_64-linux-gnu/libsndfile.so.1.0.25
7f9a361d0000-7f9a361d2000 r--p 00062000 fc:01 1579542                    /usr/lib/x86_64-linux-gnu/libsndfile.so.1.0.25
7f9a361d2000-7f9a361d3000 rw-p 00064000 fc:01 1579542                    /usr/lib/x86_64-linux-gnu/libsndfile.so.1.0.25
7f9a361d3000-7f9a361d8000 rw-p 00000000 00:00 0
7f9a361d8000-7f9a361e0000 r-xp 00000000 fc:01 31724006                   /lib/x86_64-linux-gnu/libwrap.so.0.7.6
7f9a361e0000-7f9a363df000 ---p 00008000 fc:01 31724006                   /lib/x86_64-linux-gnu/libwrap.so.0.7.6
7f9a363df000-7f9a363e0000 r--p 00007000 fc:01 31724006                   /lib/x86_64-linux-gnu/libwrap.so.0.7.6
7f9a363e0000-7f9a363e1000 rw-p 00008000 fc:01 31724006                   /lib/x86_64-linux-gnu/libwrap.so.0.7.6
7f9a363e1000-7f9a363e2000 rw-p 00000000 00:00 0
7f9a363e2000-7f9a36462000 r-xp 00000000 fc:01 31721281                   /lib/x86_64-linux-gnu/libsystemd.so.0.14.0
7f9a36462000-7f9a36465000 r--p 0007f000 fc:01 31721281                   /lib/x86_64-linux-gnu/libsystemd.so.0.14.0
7f9a36465000-7f9a36466000 rw-p 00082000 fc:01 31721281                   /lib/x86_64-linux-gnu/libsystemd.so.0.14.0
7f9a36466000-7f9a36467000 rw-p 00000000 00:00 0
7f9a36467000-7f9a36485000 r-xp 00000000 fc:01 31731816                   /lib/x86_64-linux-gnu/libudev.so.1.6.4
7f9a36485000-7f9a36486000 r--p 0001d000 fc:01 31731816                   /lib/x86_64-linux-gnu/libudev.so.1.6.4
7f9a36486000-7f9a36487000 rw-p 0001e000 fc:01 31731816                   /lib/x86_64-linux-gnu/libudev.so.1.6.4
7f9a36487000-7f9a36488000 rw-p 00000000 00:00 0
7f9a36488000-7f9a3651a000 r-xp 00000000 fc:01 1583266                    /usr/lib/x86_64-linux-gnu/libflite_cmulex.so.2.0.0
7f9a3651a000-7f9a36719000 ---p 00092000 fc:01 1583266                    /usr/lib/x86_64-linux-gnu/libflite_cmulex.so.2.0.0
7f9a36719000-7f9a3671c000 r--p 00091000 fc:01 1583266                    /usr/lib/x86_64-linux-gnu/libflite_cmulex.so.2.0.0
7f9a3671c000-7f9a3671d000 rw-p 00094000 fc:01 1583266                    /usr/lib/x86_64-linux-gnu/libflite_cmulex.so.2.0.0
7f9a3671d000-7f9a3673a000 r-xp 00000000 fc:01 1583261                    /usr/lib/x86_64-linux-gnu/libflite_usenglish.so.2.0.0
7f9a3673a000-7f9a36939000 ---p 0001d000 fc:01 1583261                    /usr/lib/x86_64-linux-gnu/libflite_usenglish.so.2.0.0
7f9a36939000-7f9a36945000 r--p 0001c000 fc:01 1583261                    /usr/lib/x86_64-linux-gnu/libflite_usenglish.so.2.0.0
7f9a36945000-7f9a36946000 rw-p 00028000 fc:01 1583261                    /usr/lib/x86_64-linux-gnu/libflite_usenglish.so.2.0.0
7f9a36946000-7f9a36947000 rw-p 00000000 00:00 0
7f9a36947000-7f9a3697e000 r-xp 00000000 fc:01 1583284                    /usr/lib/x86_64-linux-gnu/libtbb.so.2
7f9a3697e000-7f9a36b7e000 ---p 00037000 fc:01 1583284                    /usr/lib/x86_64-linux-gnu/libtbb.so.2
7f9a36b7e000-7f9a36b7f000 r--p 00037000 fc:01 1583284                    /usr/lib/x86_64-linux-gnu/libtbb.so.2
7f9a36b7f000-7f9a36b81000 rw-p 00038000 fc:01 1583284                    /usr/lib/x86_64-linux-gnu/libtbb.so.2
7f9a36b81000-7f9a36b84000 rw-p 00000000 00:00 0
7f9a36b84000-7f9a36ba5000 r-xp 00000000 fc:01 1573672                    /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
7f9a36ba5000-7f9a36da4000 ---p 00021000 fc:01 1573672                    /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
7f9a36da4000-7f9a36da5000 r--p 00020000 fc:01 1573672                    /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
7f9a36da5000-7f9a36da6000 rw-p 00021000 fc:01 1573672                    /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
7f9a36da6000-7f9a36da7000 rw-p 00000000 00:00 0
7f9a36da7000-7f9a3865d000 r-xp 00000000 fc:01 1575479                    /usr/lib/x86_64-linux-gnu/libicudata.so.55.1
7f9a3865d000-7f9a3885c000 ---p 018b6000 fc:01 1575479                    /usr/lib/x86_64-linux-gnu/libicudata.so.55.1
7f9a3885c000-7f9a3885d000 r--p 018b5000 fc:01 1575479                    /usr/lib/x86_64-linux-gnu/libicudata.so.55.1
7f9a3885d000-7f9a3885e000 rw-p 018b6000 fc:01 1575479                    /usr/lib/x86_64-linux-gnu/libicudata.so.55.1
7f9a3885e000-7f9a38882000 r-xp 00000000 fc:01 1575609                    /usr/lib/x86_64-linux-gnu/libgraphite2.so.3.0.1
7f9a38882000-7f9a38a81000 ---p 00024000 fc:01 1575609                    /usr/lib/x86_64-linux-gnu/libgraphite2.so.3.0.1
7f9a38a81000-7f9a38a83000 r--p 00023000 fc:01 1575609                    /usr/lib/x86_64-linux-gnu/libgraphite2.so.3.0.1
7f9a38a83000-7f9a38a84000 rw-p 00025000 fc:01 1575609                    /usr/lib/x86_64-linux-gnu/libgraphite2.so.3.0.1
7f9a38a84000-7f9a38a85000 rw-p 00000000 00:00 0
7f9a38a85000-7f9a38aab000 r-xp 00000000 fc:01 31731167                   /lib/x86_64-linux-gnu/libexpat.so.1.6.0
7f9a38aab000-7f9a38cab000 ---p 00026000 fc:01 31731167                   /lib/x86_64-linux-gnu/libexpat.so.1.6.0
7f9a38cab000-7f9a38cad000 r--p 00026000 fc:01 31731167                   /lib/x86_64-linux-gnu/libexpat.so.1.6.0
7f9a38cad000-7f9a38cae000 rw-p 00028000 fc:01 31731167                   /lib/x86_64-linux-gnu/libexpat.so.1.6.0
7f9a38cae000-7f9a38cb6000 r-xp 00000000 fc:01 1581855                    /usr/lib/x86_64-linux-gnu/libthai.so.0.2.4
7f9a38cb6000-7f9a38eb5000 ---p 00008000 fc:01 1581855                    /usr/lib/x86_64-linux-gnu/libthai.so.0.2.4
7f9a38eb5000-7f9a38eb6000 r--p 00007000 fc:01 1581855                    /usr/lib/x86_64-linux-gnu/libthai.so.0.2.4
7f9a38eb6000-7f9a38eb7000 rw-p 00008000 fc:01 1581855                    /usr/lib/x86_64-linux-gnu/libthai.so.0.2.4
7f9a38eb7000-7f9a38eb8000 rw-p 00000000 00:00 0
7f9a38eb8000-7f9a38ec9000 r-xp 00000000 fc:01 1575134                    /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.1
7f9a38ec9000-7f9a390c9000 ---p 00011000 fc:01 1575134                    /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.1
7f9a390c9000-7f9a390ca000 r--p 00011000 fc:01 1575134                    /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.1
7f9a390ca000-7f9a390cb000 rw-p 00012000 fc:01 1575134                    /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.1
7f9a390cb000-7f9a390fc000 r-xp 00000000 fc:01 1572878                    /usr/lib/x86_64-linux-gnu/libidn.so.11.6.15
7f9a390fc000-7f9a392fc000 ---p 00031000 fc:01 1572878                    /usr/lib/x86_64-linux-gnu/libidn.so.11.6.15
7f9a392fc000-7f9a392fd000 r--p 00031000 fc:01 1572878                    /usr/lib/x86_64-linux-gnu/libidn.so.11.6.15
7f9a392fd000-7f9a392fe000 rw-p 00032000 fc:01 1572878                    /usr/lib/x86_64-linux-gnu/libidn.so.11.6.15
7f9a392fe000-7f9a39357000 r-xp 00000000 fc:01 1575407                    /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.1.0
7f9a39357000-7f9a39556000 ---p 00059000 fc:01 1575407                    /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.1.0
7f9a39556000-7f9a39560000 r--p 00058000 fc:01 1575407                    /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.1.0
7f9a39560000-7f9a39562000 rw-p 00062000 fc:01 1575407                    /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.1.0
7f9a39562000-7f9a39563000 rw-p 00000000 00:00 0
7f9a39563000-7f9a39714000 r-xp 00000000 fc:01 1572877                    /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.3
7f9a39714000-7f9a39913000 ---p 001b1000 fc:01 1572877                    /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.3
7f9a39913000-7f9a3991b000 r--p 001b0000 fc:01 1572877                    /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.3
7f9a3991b000-7f9a3991d000 rw-p 001b8000 fc:01 1572877                    /usr/lib/x86_64-linux-gnu/libxml2.so.2.9.3
7f9a3991d000-7f9a3991e000 rw-p 00000000 00:00 0
7f9a3991e000-7f9a3999d000 r-xp 00000000 fc:01 1581215                    /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.0
7f9a3999d000-7f9a39b9c000 ---p 0007f000 fc:01 1581215                    /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.0
7f9a39b9c000-7f9a39b9d000 r--p 0007e000 fc:01 1581215                    /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.0
7f9a39b9d000-7f9a39b9e000 rw-p 0007f000 fc:01 1581215                    /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.0
7f9a39b9e000-7f9a39bd2000 r-xp 00000000 fc:01 1575402                    /usr/lib/x86_64-linux-gnu/libnettle.so.6.2
7f9a39bd2000-7f9a39dd1000 ---p 00034000 fc:01 1575402                    /usr/lib/x86_64-linux-gnu/libnettle.so.6.2
7f9a39dd1000-7f9a39dd3000 r--p 00033000 fc:01 1575402                    /usr/lib/x86_64-linux-gnu/libnettle.so.6.2
7f9a39dd3000-7f9a39dd4000 rw-p 00035000 fc:01 1575402                    /usr/lib/x86_64-linux-gnu/libnettle.so.6.2
7f9a39dd4000-7f9a39dd5000 rw-p 00000000 00:00 0
7f9a39dd5000-7f9a39e07000 r-xp 00000000 fc:01 1575400                    /usr/lib/x86_64-linux-gnu/libhogweed.so.4.2
7f9a39e07000-7f9a3a006000 ---p 00032000 fc:01 1575400                    /usr/lib/x86_64-linux-gnu/libhogweed.so.4.2
7f9a3a006000-7f9a3a007000 r--p 00031000 fc:01 1575400                    /usr/lib/x86_64-linux-gnu/libhogweed.so.4.2
7f9a3a007000-7f9a3a008000 rw-p 00032000 fc:01 1575400                    /usr/lib/x86_64-linux-gnu/libhogweed.so.4.2
7f9a3a008000-7f9a3a04f000 r-xp 00000000 fc:01 1573366                    /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
7f9a3a04f000-7f9a3a24e000 ---p 00047000 fc:01 1573366                    /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
7f9a3a24e000-7f9a3a250000 r--p 00046000 fc:01 1573366                    /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
7f9a3a250000-7f9a3a252000 rw-p 00048000 fc:01 1573366                    /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
7f9a3a252000-7f9a3a329000 r-xp 00000000 fc:01 31727045                   /lib/x86_64-linux-gnu/libgcrypt.so.20.0.5
7f9a3a329000-7f9a3a529000 ---p 000d7000 fc:01 31727045                   /lib/x86_64-linux-gnu/libgcrypt.so.20.0.5
7f9a3a529000-7f9a3a52a000 r--p 000d7000 fc:01 31727045                   /lib/x86_64-linux-gnu/libgcrypt.so.20.0.5
7f9a3a52a000-7f9a3a532000 rw-p 000d8000 fc:01 31727045                   /lib/x86_64-linux-gnu/libgcrypt.so.20.0.5
7f9a3a532000-7f9a3a534000 rw-p 00000000 00:00 0
7f9a3a534000-7f9a3a559000 r-xp 00000000 fc:01 31723992                   /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f9a3a559000-7f9a3a758000 ---p 00025000 fc:01 31723992                   /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f9a3a758000-7f9a3a75c000 r--p 00024000 fc:01 31723992                   /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f9a3a75c000-7f9a3a75d000 rw-p 00028000 fc:01 31723992                   /lib/x86_64-linux-gnu/libtinfo.so.5.9
7f9a3a75d000-7f9a3a78a000 r-xp 00000000 fc:01 31723902                   /lib/x86_64-linux-gnu/libncursesw.so.5.9
7f9a3a78a000-7f9a3a98a000 ---p 0002d000 fc:01 31723902                   /lib/x86_64-linux-gnu/libncursesw.so.5.9
7f9a3a98a000-7f9a3a98b000 r--p 0002d000 fc:01 31723902                   /lib/x86_64-linux-gnu/libncursesw.so.5.9
7f9a3a98b000-7f9a3a98c000 rw-p 0002e000 fc:01 31723902                   /lib/x86_64-linux-gnu/libncursesw.so.5.9
7f9a3a98c000-7f9a3a98d000 rw-p 00000000 00:00 0
7f9a3a98d000-7f9a3aaa7000 r-xp 00000000 fc:01 31723981                   /lib/x86_64-linux-gnu/libslang.so.2.3.0
7f9a3aaa7000-7f9a3aca7000 ---p 0011a000 fc:01 31723981                   /lib/x86_64-linux-gnu/libslang.so.2.3.0
7f9a3aca7000-7f9a3acab000 r--p 0011a000 fc:01 31723981                   /lib/x86_64-linux-gnu/libslang.so.2.3.0
7f9a3acab000-7f9a3acc4000 rw-p 0011e000 fc:01 31723981                   /lib/x86_64-linux-gnu/libslang.so.2.3.0
7f9a3acc4000-7f9a3ad19000 rw-p 00000000 00:00 0
7f9a3ad19000-7f9a3ad63000 r-xp 00000000 fc:01 31720754                   /lib/x86_64-linux-gnu/libdbus-1.so.3.14.6
7f9a3ad63000-7f9a3af63000 ---p 0004a000 fc:01 31720754                   /lib/x86_64-linux-gnu/libdbus-1.so.3.14.6
7f9a3af63000-7f9a3af64000 r--p 0004a000 fc:01 31720754                   /lib/x86_64-linux-gnu/libdbus-1.so.3.14.6
7f9a3af64000-7f9a3af65000 rw-p 0004b000 fc:01 31720754                   /lib/x86_64-linux-gnu/libdbus-1.so.3.14.6
7f9a3af65000-7f9a3afdf000 r-xp 00000000 fc:01 1836157                    /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-8.0.so
7f9a3afdf000-7f9a3b1de000 ---p 0007a000 fc:01 1836157                    /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-8.0.so
7f9a3b1de000-7f9a3b1df000 r--p 00079000 fc:01 1836157                    /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-8.0.so
7f9a3b1df000-7f9a3b1e0000 rw-p 0007a000 fc:01 1836157                    /usr/lib/x86_64-linux-gnu/pulseaudio/libpulsecommon-8.0.so
7f9a3b1e0000-7f9a3b1e1000 rw-p 00000000 00:00 0
7f9a3b1e1000-7f9a3b1eb000 r-xp 00000000 fc:01 31723879                   /lib/x86_64-linux-gnu/libjson-c.so.2.0.0
7f9a3b1eb000-7f9a3b3ea000 ---p 0000a000 fc:01 31723879                   /lib/x86_64-linux-gnu/libjson-c.so.2.0.0
7f9a3b3ea000-7f9a3b3eb000 r--p 00009000 fc:01 31723879                   /lib/x86_64-linux-gnu/libjson-c.so.2.0.0
7f9a3b3eb000-7f9a3b3ec000 rw-p 0000a000 fc:01 31723879                   /lib/x86_64-linux-gnu/libjson-c.so.2.0.0
7f9a3b3ec000-7f9a3c88a000 r-xp 00000000 fc:01 1621287                    /usr/lib/nvidia-384/libnvidia-glcore.so.384.111
7f9a3c88a000-7f9a3c8ab000 rwxp 0149e000 fc:01 1621287                    /usr/lib/nvidia-384/libnvidia-glcore.so.384.111
7f9a3c8ab000-7f9a3cc8d000 r-xp 014bf000 fc:01 1621287                    /usr/lib/nvidia-384/libnvidia-glcore.so.384.111
7f9a3cc8d000-7f9a3ce8d000 ---p 018a1000 fc:01 1621287                    /usr/lib/nvidia-384/libnvidia-glcore.so.384.111
7f9a3ce8d000-7f9a3d290000 rw-p 018a1000 fc:01 1621287                    /usr/lib/nvidia-384/libnvidia-glcore.so.384.111
7f9a3d290000-7f9a3d2a9000 rw-p 00000000 00:00 0
7f9a3d2a9000-7f9a3d2ac000 r-xp 00000000 fc:01 1621255                    /usr/lib/nvidia-384/tls/libnvidia-tls.so.384.111
7f9a3d2ac000-7f9a3d4ac000 ---p 00003000 fc:01 1621255                    /usr/lib/nvidia-384/tls/libnvidia-tls.so.384.111
7f9a3d4ac000-7f9a3d4ad000 rw-p 00003000 fc:01 1621255                    /usr/lib/nvidia-384/tls/libnvidia-tls.so.384.111
7f9a3d4ad000-7f9a3d4ae000 rw-p 00000000 00:00 0
7f9a3d4ae000-7f9a3d4c5000 r-xp 00000000 fc:01 31724000                   /lib/x86_64-linux-gnu/libusb-1.0.so.0.1.0
7f9a3d4c5000-7f9a3d6c4000 ---p 00017000 fc:01 31724000                   /lib/x86_64-linux-gnu/libusb-1.0.so.0.1.0
7f9a3d6c4000-7f9a3d6c5000 r--p 00016000 fc:01 31724000                   /lib/x86_64-linux-gnu/libusb-1.0.so.0.1.0
7f9a3d6c5000-7f9a3d6c6000 rw-p 00017000 fc:01 31724000                   /lib/x86_64-linux-gnu/libusb-1.0.so.0.1.0
7f9a3d6c6000-7f9a3d6c9000 r-xp 00000000 fc:01 1575348                    /usr/lib/x86_64-linux-gnu/libpulse-simple.so.0.1.0
7f9a3d6c9000-7f9a3d8c9000 ---p 00003000 fc:01 1575348                    /usr/lib/x86_64-linux-gnu/libpulse-simple.so.0.1.0
7f9a3d8c9000-7f9a3d8ca000 r--p 00003000 fc:01 1575348                    /usr/lib/x86_64-linux-gnu/libpulse-simple.so.0.1.0
7f9a3d8ca000-7f9a3d8cb000 rw-p 00004000 fc:01 1575348                    /usr/lib/x86_64-linux-gnu/libpulse-simple.so.0.1.0
7f9a3d8cb000-7f9a3d8cc000 rw-p 00000000 00:00 0
7f9a3d8cc000-7f9a3d8ec000 r-xp 00000000 fc:01 1580880                    /usr/lib/x86_64-linux-gnu/libcdio.so.13.0.0
7f9a3d8ec000-7f9a3daeb000 ---p 00020000 fc:01 1580880                    /usr/lib/x86_64-linux-gnu/libcdio.so.13.0.0
7f9a3daeb000-7f9a3daec000 r--p 0001f000 fc:01 1580880                    /usr/lib/x86_64-linux-gnu/libcdio.so.13.0.0
7f9a3daec000-7f9a3daed000 rw-p 00020000 fc:01 1580880                    /usr/lib/x86_64-linux-gnu/libcdio.so.13.0.0
7f9a3daed000-7f9a3daf1000 rw-p 00000000 00:00 0
7f9a3daf1000-7f9a3daf6000 r-xp 00000000 fc:01 1580710                    /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
7f9a3daf6000-7f9a3dcf5000 ---p 00005000 fc:01 1580710                    /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
7f9a3dcf5000-7f9a3dcf6000 r--p 00004000 fc:01 1580710                    /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
7f9a3dcf6000-7f9a3dcf7000 rw-p 00005000 fc:01 1580710                    /usr/lib/x86_64-linux-gnu/libXdmcp.so.6.0.0
7f9a3dcf7000-7f9a3dcf8000 rw-p 00000000 00:00 0
7f9a3dcf8000-7f9a3dcfa000 r-xp 00000000 fc:01 1580699                    /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
7f9a3dcfa000-7f9a3defa000 ---p 00002000 fc:01 1580699                    /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
7f9a3defa000-7f9a3defb000 r--p 00002000 fc:01 1580699                    /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
7f9a3defb000-7f9a3defc000 rw-p 00003000 fc:01 1580699                    /usr/lib/x86_64-linux-gnu/libXau.so.6.0.0
7f9a3defc000-7f9a3df2b000 r-xp 00000000 fc:01 1583238                    /usr/lib/x86_64-linux-gnu/libass.so.5.2.1
7f9a3df2b000-7f9a3e12a000 ---p 0002f000 fc:01 1583238                    /usr/lib/x86_64-linux-gnu/libass.so.5.2.1
7f9a3e12a000-7f9a3e12b000 r--p 0002e000 fc:01 1583238                    /usr/lib/x86_64-linux-gnu/libass.so.5.2.1
7f9a3e12b000-7f9a3e12c000 rw-p 0002f000 fc:01 1583238                    /usr/lib/x86_64-linux-gnu/libass.so.5.2.1
7f9a3e12c000-7f9a3e12d000 rw-p 00000000 00:00 0
7f9a3e12d000-7f9a3e131000 r-xp 00000000 fc:01 1583254                    /usr/lib/x86_64-linux-gnu/libbs2b.so.0.0.0
7f9a3e131000-7f9a3e331000 ---p 00004000 fc:01 1583254                    /usr/lib/x86_64-linux-gnu/libbs2b.so.0.0.0
7f9a3e331000-7f9a3e332000 r--p 00004000 fc:01 1583254                    /usr/lib/x86_64-linux-gnu/libbs2b.so.0.0.0
7f9a3e332000-7f9a3e333000 rw-p 00005000 fc:01 1583254                    /usr/lib/x86_64-linux-gnu/libbs2b.so.0.0.0
7f9a3e333000-7f9a3e367000 r-xp 00000000 fc:01 1583262                    /usr/lib/x86_64-linux-gnu/libflite.so.2.0.0
7f9a3e367000-7f9a3e566000 ---p 00034000 fc:01 1583262                    /usr/lib/x86_64-linux-gnu/libflite.so.2.0.0
7f9a3e566000-7f9a3e568000 r--p 00033000 fc:01 1583262                    /usr/lib/x86_64-linux-gnu/libflite.so.2.0.0
7f9a3e568000-7f9a3e569000 rw-p 00035000 fc:01 1583262                    /usr/lib/x86_64-linux-gnu/libflite.so.2.0.0
7f9a3e569000-7f9a3e8d3000 r-xp 00000000 fc:01 1583258                    /usr/lib/x86_64-linux-gnu/libflite_cmu_us_slt.so.2.0.0
7f9a3e8d3000-7f9a3ead2000 ---p 0036a000 fc:01 1583258                    /usr/lib/x86_64-linux-gnu/libflite_cmu_us_slt.so.2.0.0
7f9a3ead2000-7f9a3eb5e000 r--p 00369000 fc:01 1583258                    /usr/lib/x86_64-linux-gnu/libflite_cmu_us_slt.so.2.0.0
7f9a3eb5e000-7f9a3eb5f000 rw-p 003f5000 fc:01 1583258                    /usr/lib/x86_64-linux-gnu/libflite_cmu_us_slt.so.2.0.0
7f9a3eb5f000-7f9a3eb60000 rw-p 00000000 00:00 0
7f9a3eb60000-7f9a3ef59000 r-xp 00000000 fc:01 1583267                    /usr/lib/x86_64-linux-gnu/libflite_cmu_us_rms.so.2.0.0
7f9a3ef59000-7f9a3f158000 ---p 003f9000 fc:01 1583267                    /usr/lib/x86_64-linux-gnu/libflite_cmu_us_rms.so.2.0.0
7f9a3f158000-7f9a3f1f7000 r--p 003f8000 fc:01 1583267                    /usr/lib/x86_64-linux-gnu/libflite_cmu_us_rms.so.2.0.0
7f9a3f1f7000-7f9a3f1f8000 rw-p 00497000 fc:01 1583267                    /usr/lib/x86_64-linux-gnu/libflite_cmu_us_rms.so.2.0.0
7f9a3f1f8000-7f9a3f5c8000 r-xp 00000000 fc:01 1583256                    /usr/lib/x86_64-linux-gnu/libflite_cmu_us_kal16.so.2.0.0
7f9a3f5c8000-7f9a3f7c7000 ---p 003d0000 fc:01 1583256                    /usr/lib/x86_64-linux-gnu/libflite_cmu_us_kal16.so.2.0.0
7f9a3f7c7000-7f9a3f7ce000 r--p 003cf000 fc:01 1583256                    /usr/lib/x86_64-linux-gnu/libflite_cmu_us_kal16.so.2.0.0
7f9a3f7ce000-7f9a3f7cf000 rw-p 003d6000 fc:01 1583256                    /usr/lib/x86_64-linux-gnu/libflite_cmu_us_kal16.so.2.0.0
7f9a3f7cf000-7f9a3f92a000 r-xp 00000000 fc:01 1583264                    /usr/lib/x86_64-linux-gnu/libflite_cmu_us_kal.so.2.0.0
7f9a3f92a000-7f9a3fb2a000 ---p 0015b000 fc:01 1583264                    /usr/lib/x86_64-linux-gnu/libflite_cmu_us_kal.so.2.0.0
7f9a3fb2a000-7f9a3fb31000 r--p 0015b000 fc:01 1583264                    /usr/lib/x86_64-linux-gnu/libflite_cmu_us_kal.so.2.0.0
7f9a3fb31000-7f9a3fb32000 rw-p 00162000 fc:01 1583264                    /usr/lib/x86_64-linux-gnu/libflite_cmu_us_kal.so.2.0.0
7f9a3fb32000-7f9a3fb33000 rw-p 00000000 00:00 0
7f9a3fb33000-7f9a3fe9c000 r-xp 00000000 fc:01 1583268                    /usr/lib/x86_64-linux-gnu/libflite_cmu_us_awb.so.2.0.0
7f9a3fe9c000-7f9a4009b000 ---p 00369000 fc:01 1583268                    /usr/lib/x86_64-linux-gnu/libflite_cmu_us_awb.so.2.0.0
7f9a4009b000-7f9a40127000 r--p 00368000 fc:01 1583268                    /usr/lib/x86_64-linux-gnu/libflite_cmu_us_awb.so.2.0.0
7f9a40127000-7f9a40128000 rw-p 003f4000 fc:01 1583268                    /usr/lib/x86_64-linux-gnu/libflite_cmu_us_awb.so.2.0.0
7f9a40128000-7f9a4013e000 r-xp 00000000 fc:01 1581132                    /usr/lib/x86_64-linux-gnu/libfribidi.so.0.3.6
7f9a4013e000-7f9a4033d000 ---p 00016000 fc:01 1581132                    /usr/lib/x86_64-linux-gnu/libfribidi.so.0.3.6
7f9a4033d000-7f9a4033e000 r--p 00015000 fc:01 1581132                    /usr/lib/x86_64-linux-gnu/libfribidi.so.0.3.6
7f9a4033e000-7f9a4033f000 rw-p 00016000 fc:01 1581132                    /usr/lib/x86_64-linux-gnu/libfribidi.so.0.3.6
7f9a4033f000-7f9a4052f000 r-xp 00000000 fc:01 1583287                    /usr/lib/x86_64-linux-gnu/libopencv_imgproc.so.2.4.9
7f9a4052f000-7f9a4072e000 ---p 001f0000 fc:01 1583287                    /usr/lib/x86_64-linux-gnu/libopencv_imgproc.so.2.4.9
7f9a4072e000-7f9a40734000 r--p 001ef000 fc:01 1583287                    /usr/lib/x86_64-linux-gnu/libopencv_imgproc.so.2.4.9
7f9a40734000-7f9a40735000 rw-p 001f5000 fc:01 1583287                    /usr/lib/x86_64-linux-gnu/libopencv_imgproc.so.2.4.9
7f9a40735000-7f9a407cb000 rw-p 00000000 00:00 0
7f9a407cb000-7f9a409e8000 r-xp 00000000 fc:01 1583285                    /usr/lib/x86_64-linux-gnu/libopencv_core.so.2.4.9
7f9a409e8000-7f9a40be8000 ---p 0021d000 fc:01 1583285                    /usr/lib/x86_64-linux-gnu/libopencv_core.so.2.4.9
7f9a40be8000-7f9a40bec000 r--p 0021d000 fc:01 1583285                    /usr/lib/x86_64-linux-gnu/libopencv_core.so.2.4.9
7f9a40bec000-7f9a40bf3000 rw-p 00221000 fc:01 1583285                    /usr/lib/x86_64-linux-gnu/libopencv_core.so.2.4.9
7f9a40bf3000-7f9a40bf5000 rw-p 00000000 00:00 0
7f9a40bf5000-7f9a40c57000 r-xp 00000000 fc:01 1583295                    /usr/lib/x86_64-linux-gnu/libzmq.so.5.0.0
7f9a40c57000-7f9a40e56000 ---p 00062000 fc:01 1583295                    /usr/lib/x86_64-linux-gnu/libzmq.so.5.0.0
7f9a40e56000-7f9a40e5a000 r--p 00061000 fc:01 1583295                    /usr/lib/x86_64-linux-gnu/libzmq.so.5.0.0
7f9a40e5a000-7f9a40e5b000 rw-p 00065000 fc:01 1583295                    /usr/lib/x86_64-linux-gnu/libzmq.so.5.0.0
7f9a40e5b000-7f9a40e7b000 r-xp 00000000 fc:01 1583252                    /usr/lib/x86_64-linux-gnu/libavresample-ffmpeg.so.2.1.0
7f9a40e7b000-7f9a4107a000 ---p 00020000 fc:01 1583252                    /usr/lib/x86_64-linux-gnu/libavresample-ffmpeg.so.2.1.0
7f9a4107a000-7f9a4107c000 r--p 0001f000 fc:01 1583252                    /usr/lib/x86_64-linux-gnu/libavresample-ffmpeg.so.2.1.0
7f9a4107c000-7f9a4107d000 rw-p 00021000 fc:01 1583252                    /usr/lib/x86_64-linux-gnu/libavresample-ffmpeg.so.2.1.0
7f9a4107d000-7f9a4107e000 rw-p 00000000 00:00 0
7f9a4107e000-7f9a41099000 r-xp 00000000 fc:01 1583289                    /usr/lib/x86_64-linux-gnu/libpostproc-ffmpeg.so.53.3.100
7f9a41099000-7f9a41298000 ---p 0001b000 fc:01 1583289                    /usr/lib/x86_64-linux-gnu/libpostproc-ffmpeg.so.53.3.100
7f9a41298000-7f9a41299000 r--p 0001a000 fc:01 1583289                    /usr/lib/x86_64-linux-gnu/libpostproc-ffmpeg.so.53.3.100
7f9a41299000-7f9a4129a000 rw-p 0001b000 fc:01 1583289                    /usr/lib/x86_64-linux-gnu/libpostproc-ffmpeg.so.53.3.100
7f9a4129a000-7f9a41315000 r-xp 00000000 fc:01 1581612                    /usr/lib/x86_64-linux-gnu/liborc-0.4.so.0.25.0
7f9a41315000-7f9a41514000 ---p 0007b000 fc:01 1581612                    /usr/lib/x86_64-linux-gnu/liborc-0.4.so.0.25.0
7f9a41514000-7f9a41516000 r--p 0007a000 fc:01 1581612                    /usr/lib/x86_64-linux-gnu/liborc-0.4.so.0.25.0
7f9a41516000-7f9a4151a000 rw-p 0007c000 fc:01 1581612                    /usr/lib/x86_64-linux-gnu/liborc-0.4.so.0.25.0
7f9a4151a000-7f9a4151b000 rw-p 00000000 00:00 0
7f9a4151b000-7f9a41522000 r-xp 00000000 fc:01 1581606                    /usr/lib/x86_64-linux-gnu/libogg.so.0.8.2
7f9a41522000-7f9a41722000 ---p 00007000 fc:01 1581606                    /usr/lib/x86_64-linux-gnu/libogg.so.0.8.2
7f9a41722000-7f9a41723000 r--p 00007000 fc:01 1581606                    /usr/lib/x86_64-linux-gnu/libogg.so.0.8.2
7f9a41723000-7f9a41724000 rw-p 00008000 fc:01 1581606                    /usr/lib/x86_64-linux-gnu/libogg.so.0.8.2
7f9a41724000-7f9a4172e000 r-xp 00000000 fc:01 1576177                    /usr/lib/x86_64-linux-gnu/libnuma.so.1.0.0
7f9a4172e000-7f9a4192d000 ---p 0000a000 fc:01 1576177                    /usr/lib/x86_64-linux-gnu/libnuma.so.1.0.0
7f9a4192d000-7f9a4192e000 r--p 00009000 fc:01 1576177                    /usr/lib/x86_64-linux-gnu/libnuma.so.1.0.0
7f9a4192e000-7f9a4192f000 rw-p 0000a000 fc:01 1576177                    /usr/lib/x86_64-linux-gnu/libnuma.so.1.0.0
7f9a4192f000-7f9a41930000 rw-p 00000000 00:00 0
7f9a41930000-7f9a4195e000 r-xp 00000000 fc:01 1583218                    /usr/lib/x86_64-linux-gnu/libsoxr.so.0.1.1
7f9a4195e000-7f9a41b5d000 ---p 0002e000 fc:01 1583218                    /usr/lib/x86_64-linux-gnu/libsoxr.so.0.1.1
7f9a41b5d000-7f9a41b5f000 r--p 0002d000 fc:01 1583218                    /usr/lib/x86_64-linux-gnu/libsoxr.so.0.1.1
7f9a41b5f000-7f9a41b60000 rw-p 0002f000 fc:01 1583218                    /usr/lib/x86_64-linux-gnu/libsoxr.so.0.1.1
7f9a41b60000-7f9a41b95000 rw-p 00000000 00:00 0
7f9a41b95000-7f9a41bab000 r-xp 00000000 fc:01 31723858                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f9a41bab000-7f9a41daa000 ---p 00016000 fc:01 31723858                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f9a41daa000-7f9a41dab000 rw-p 00015000 fc:01 31723858                   /lib/x86_64-linux-gnu/libgcc_s.so.1
7f9a41dab000-7f9a41dac000 rw-p 00000000 00:00 0
7f9a41dac000-7f9a41e10000 r-xp 00000000 fc:01 1581648                    /usr/lib/x86_64-linux-gnu/libpcre16.so.3.13.2
7f9a41e10000-7f9a42010000 ---p 00064000 fc:01 1581648                    /usr/lib/x86_64-linux-gnu/libpcre16.so.3.13.2
7f9a42010000-7f9a42011000 r--p 00064000 fc:01 1581648                    /usr/lib/x86_64-linux-gnu/libpcre16.so.3.13.2
7f9a42011000-7f9a42012000 rw-p 00065000 fc:01 1581648                    /usr/lib/x86_64-linux-gnu/libpcre16.so.3.13.2
7f9a42012000-7f9a42191000 r-xp 00000000 fc:01 1575481                    /usr/lib/x86_64-linux-gnu/libicuuc.so.55.1
7f9a42191000-7f9a42391000 ---p 0017f000 fc:01 1575481                    /usr/lib/x86_64-linux-gnu/libicuuc.so.55.1
7f9a42391000-7f9a423a1000 r--p 0017f000 fc:01 1575481                    /usr/lib/x86_64-linux-gnu/libicuuc.so.55.1
7f9a423a1000-7f9a423a2000 rw-p 0018f000 fc:01 1575481                    /usr/lib/x86_64-linux-gnu/libicuuc.so.55.1
7f9a423a2000-7f9a423a6000 rw-p 00000000 00:00 0
7f9a423a6000-7f9a425f8000 r-xp 00000000 fc:01 1575473                    /usr/lib/x86_64-linux-gnu/libicui18n.so.55.1
7f9a425f8000-7f9a427f8000 ---p 00252000 fc:01 1575473                    /usr/lib/x86_64-linux-gnu/libicui18n.so.55.1
7f9a427f8000-7f9a42807000 r--p 00252000 fc:01 1575473                    /usr/lib/x86_64-linux-gnu/libicui18n.so.55.1
7f9a42807000-7f9a42808000 rw-p 00261000 fc:01 1575473                    /usr/lib/x86_64-linux-gnu/libicui18n.so.55.1
7f9a42808000-7f9a42809000 rw-p 00000000 00:00 0
7f9a42809000-7f9a42865000 r-xp 00000000 fc:01 1578201                    /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0.10000.1
7f9a42865000-7f9a42a65000 ---p 0005c000 fc:01 1578201                    /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0.10000.1
7f9a42a65000-7f9a42a66000 r--p 0005c000 fc:01 1578201                    /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0.10000.1
7f9a42a66000-7f9a42a67000 rw-p 0005d000 fc:01 1578201                    /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0.10000.1
7f9a42a67000-7f9a42a7e000 r-xp 00000000 fc:01 31748884                   /lib/x86_64-linux-gnu/libresolv-2.23.so
7f9a42a7e000-7f9a42c7e000 ---p 00017000 fc:01 31748884                   /lib/x86_64-linux-gnu/libresolv-2.23.so
7f9a42c7e000-7f9a42c7f000 r--p 00017000 fc:01 31748884                   /lib/x86_64-linux-gnu/libresolv-2.23.so
7f9a42c7f000-7f9a42c80000 rw-p 00018000 fc:01 31748884                   /lib/x86_64-linux-gnu/libresolv-2.23.so
7f9a42c80000-7f9a42c82000 rw-p 00000000 00:00 0
7f9a42c82000-7f9a42ca1000 r-xp 00000000 fc:01 31723978                   /lib/x86_64-linux-gnu/libselinux.so.1
7f9a42ca1000-7f9a42ea0000 ---p 0001f000 fc:01 31723978                   /lib/x86_64-linux-gnu/libselinux.so.1
7f9a42ea0000-7f9a42ea1000 r--p 0001e000 fc:01 31723978                   /lib/x86_64-linux-gnu/libselinux.so.1
7f9a42ea1000-7f9a42ea2000 rw-p 0001f000 fc:01 31723978                   /lib/x86_64-linux-gnu/libselinux.so.1
7f9a42ea2000-7f9a42ea5000 rw-p 00000000 00:00 0
7f9a42ea5000-7f9a42ead000 r-xp 00000000 fc:01 1582063                    /usr/lib/x86_64-linux-gnu/libxcb-render.so.0.0.0
7f9a42ead000-7f9a430ad000 ---p 00008000 fc:01 1582063                    /usr/lib/x86_64-linux-gnu/libxcb-render.so.0.0.0
7f9a430ad000-7f9a430ae000 r--p 00008000 fc:01 1582063                    /usr/lib/x86_64-linux-gnu/libxcb-render.so.0.0.0
7f9a430ae000-7f9a430af000 rw-p 00009000 fc:01 1582063                    /usr/lib/x86_64-linux-gnu/libxcb-render.so.0.0.0
7f9a430af000-7f9a430d3000 r-xp 00000000 fc:01 31723961                   /lib/x86_64-linux-gnu/libpng12.so.0.54.0
7f9a430d3000-7f9a432d2000 ---p 00024000 fc:01 31723961                   /lib/x86_64-linux-gnu/libpng12.so.0.54.0
7f9a432d2000-7f9a432d3000 r--p 00023000 fc:01 31723961                   /lib/x86_64-linux-gnu/libpng12.so.0.54.0
7f9a432d3000-7f9a432d4000 rw-p 00024000 fc:01 31723961                   /lib/x86_64-linux-gnu/libpng12.so.0.54.0
7f9a432d4000-7f9a43378000 r-xp 00000000 fc:01 1575385                    /usr/lib/x86_64-linux-gnu/libfreetype.so.6.12.1
7f9a43378000-7f9a43577000 ---p 000a4000 fc:01 1575385                    /usr/lib/x86_64-linux-gnu/libfreetype.so.6.12.1
7f9a43577000-7f9a4357d000 r--p 000a3000 fc:01 1575385                    /usr/lib/x86_64-linux-gnu/libfreetype.so.6.12.1
7f9a4357d000-7f9a4357e000 rw-p 000a9000 fc:01 1575385                    /usr/lib/x86_64-linux-gnu/libfreetype.so.6.12.1
7f9a4357e000-7f9a4357f000 rw-p 00000000 00:00 0
7f9a4357f000-7f9a4361e000 r-xp 00000000 fc:01 1581660                    /usr/lib/x86_64-linux-gnu/libpixman-1.so.0.33.6
7f9a4361e000-7f9a4381e000 ---p 0009f000 fc:01 1581660                    /usr/lib/x86_64-linux-gnu/libpixman-1.so.0.33.6
7f9a4381e000-7f9a43826000 r--p 0009f000 fc:01 1581660                    /usr/lib/x86_64-linux-gnu/libpixman-1.so.0.33.6
7f9a43826000-7f9a43827000 rw-p 000a7000 fc:01 1581660                    /usr/lib/x86_64-linux-gnu/libpixman-1.so.0.33.6
7f9a43827000-7f9a43829000 r-xp 00000000 fc:01 1580708                    /usr/lib/x86_64-linux-gnu/libXdamage.so.1.1.0
7f9a43829000-7f9a43a28000 ---p 00002000 fc:01 1580708                    /usr/lib/x86_64-linux-gnu/libXdamage.so.1.1.0
7f9a43a28000-7f9a43a29000 r--p 00001000 fc:01 1580708                    /usr/lib/x86_64-linux-gnu/libXdamage.so.1.1.0
7f9a43a29000-7f9a43a2a000 rw-p 00002000 fc:01 1580708                    /usr/lib/x86_64-linux-gnu/libXdamage.so.1.1.0
7f9a43a2a000-7f9a43a2c000 r-xp 00000000 fc:01 1580704                    /usr/lib/x86_64-linux-gnu/libXcomposite.so.1.0.0
7f9a43a2c000-7f9a43c2b000 ---p 00002000 fc:01 1580704                    /usr/lib/x86_64-linux-gnu/libXcomposite.so.1.0.0
7f9a43c2b000-7f9a43c2c000 r--p 00001000 fc:01 1580704                    /usr/lib/x86_64-linux-gnu/libXcomposite.so.1.0.0
7f9a43c2c000-7f9a43c2d000 rw-p 00002000 fc:01 1580704                    /usr/lib/x86_64-linux-gnu/libXcomposite.so.1.0.0
7f9a43c2d000-7f9a43c36000 r-xp 00000000 fc:01 1580193                    /usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2
7f9a43c36000-7f9a43e35000 ---p 00009000 fc:01 1580193                    /usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2
7f9a43e35000-7f9a43e36000 r--p 00008000 fc:01 1580193                    /usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2
7f9a43e36000-7f9a43e37000 rw-p 00009000 fc:01 1580193                    /usr/lib/x86_64-linux-gnu/libXcursor.so.1.0.2
7f9a43e37000-7f9a43e41000 r-xp 00000000 fc:01 1580730                    /usr/lib/x86_64-linux-gnu/libXrandr.so.2.2.0
7f9a43e41000-7f9a44040000 ---p 0000a000 fc:01 1580730                    /usr/lib/x86_64-linux-gnu/libXrandr.so.2.2.0
7f9a44040000-7f9a44041000 r--p 00009000 fc:01 1580730                    /usr/lib/x86_64-linux-gnu/libXrandr.so.2.2.0
7f9a44041000-7f9a44042000 rw-p 0000a000 fc:01 1580730                    /usr/lib/x86_64-linux-gnu/libXrandr.so.2.2.0
7f9a44042000-7f9a44051000 r-xp 00000000 fc:01 1580720                    /usr/lib/x86_64-linux-gnu/libXi.so.6.1.0
7f9a44051000-7f9a44250000 ---p 0000f000 fc:01 1580720                    /usr/lib/x86_64-linux-gnu/libXi.so.6.1.0
7f9a44250000-7f9a44251000 r--p 0000e000 fc:01 1580720                    /usr/lib/x86_64-linux-gnu/libXi.so.6.1.0
7f9a44251000-7f9a44252000 rw-p 0000f000 fc:01 1580720                    /usr/lib/x86_64-linux-gnu/libXi.so.6.1.0
7f9a44252000-7f9a44254000 r-xp 00000000 fc:01 1580722                    /usr/lib/x86_64-linux-gnu/libXinerama.so.1.0.0
7f9a44254000-7f9a44453000 ---p 00002000 fc:01 1580722                    /usr/lib/x86_64-linux-gnu/libXinerama.so.1.0.0
7f9a44453000-7f9a44454000 r--p 00001000 fc:01 1580722                    /usr/lib/x86_64-linux-gnu/libXinerama.so.1.0.0
7f9a44454000-7f9a44455000 rw-p 00002000 fc:01 1580722                    /usr/lib/x86_64-linux-gnu/libXinerama.so.1.0.0
7f9a44455000-7f9a4445e000 r-xp 00000000 fc:01 1580732                    /usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
7f9a4445e000-7f9a4465d000 ---p 00009000 fc:01 1580732                    /usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
7f9a4465d000-7f9a4465e000 r--p 00008000 fc:01 1580732                    /usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
7f9a4465e000-7f9a4465f000 rw-p 00009000 fc:01 1580732                    /usr/lib/x86_64-linux-gnu/libXrender.so.1.3.0
7f9a4465f000-7f9a4469c000 r-xp 00000000 fc:01 1574419                    /usr/lib/x86_64-linux-gnu/libfontconfig.so.1.9.0
7f9a4469c000-7f9a4489b000 ---p 0003d000 fc:01 1574419                    /usr/lib/x86_64-linux-gnu/libfontconfig.so.1.9.0
7f9a4489b000-7f9a4489d000 r--p 0003c000 fc:01 1574419                    /usr/lib/x86_64-linux-gnu/libfontconfig.so.1.9.0
7f9a4489d000-7f9a448a2000 rw-p 0003e000 fc:01 1574419                    /usr/lib/x86_64-linux-gnu/libfontconfig.so.1.9.0
7f9a448a2000-7f9a448eb000 r-xp 00000000 fc:01 1581632                    /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0.3800.1
7f9a448eb000-7f9a44aeb000 ---p 00049000 fc:01 1581632                    /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0.3800.1
7f9a44aeb000-7f9a44aed000 r--p 00049000 fc:01 1581632                    /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0.3800.1
7f9a44aed000-7f9a44aee000 rw-p 0004b000 fc:01 1581632                    /usr/lib/x86_64-linux-gnu/libpango-1.0.so.0.3800.1
7f9a44aee000-7f9a44b02000 r-xp 00000000 fc:01 1581636                    /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0.3800.1
7f9a44b02000-7f9a44d02000 ---p 00014000 fc:01 1581636                    /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0.3800.1
7f9a44d02000-7f9a44d03000 r--p 00014000 fc:01 1581636                    /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0.3800.1
7f9a44d03000-7f9a44d04000 rw-p 00015000 fc:01 1581636                    /usr/lib/x86_64-linux-gnu/libpangoft2-1.0.so.0.3800.1
7f9a44d04000-7f9a44d26000 r-xp 00000000 fc:01 1580803                    /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0.21809.1
7f9a44d26000-7f9a44f25000 ---p 00022000 fc:01 1580803                    /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0.21809.1
7f9a44f25000-7f9a44f28000 r--p 00021000 fc:01 1580803                    /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0.21809.1
7f9a44f28000-7f9a44f29000 rw-p 00024000 fc:01 1580803                    /usr/lib/x86_64-linux-gnu/libatk-1.0.so.0.21809.1
7f9a44f29000-7f9a44f2e000 r-xp 00000000 fc:01 1580714                    /usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
7f9a44f2e000-7f9a4512d000 ---p 00005000 fc:01 1580714                    /usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
7f9a4512d000-7f9a4512e000 r--p 00004000 fc:01 1580714                    /usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
7f9a4512e000-7f9a4512f000 rw-p 00005000 fc:01 1580714                    /usr/lib/x86_64-linux-gnu/libXfixes.so.3.1.0
7f9a4512f000-7f9a4513b000 r-xp 00000000 fc:01 1581634                    /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0.3800.1
7f9a4513b000-7f9a4533a000 ---p 0000c000 fc:01 1581634                    /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0.3800.1
7f9a4533a000-7f9a4533b000 r--p 0000b000 fc:01 1581634                    /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0.3800.1
7f9a4533b000-7f9a4533c000 rw-p 0000c000 fc:01 1581634                    /usr/lib/x86_64-linux-gnu/libpangocairo-1.0.so.0.3800.1
7f9a4533c000-7f9a453aa000 r-xp 00000000 fc:01 31723949                   /lib/x86_64-linux-gnu/libpcre.so.3.13.2
7f9a453aa000-7f9a455aa000 ---p 0006e000 fc:01 31723949                   /lib/x86_64-linux-gnu/libpcre.so.3.13.2
7f9a455aa000-7f9a455ab000 r--p 0006e000 fc:01 31723949                   /lib/x86_64-linux-gnu/libpcre.so.3.13.2
7f9a455ab000-7f9a455ac000 rw-p 0006f000 fc:01 31723949                   /lib/x86_64-linux-gnu/libpcre.so.3.13.2
7f9a455ac000-7f9a455b3000 r-xp 00000000 fc:01 1581082                    /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
7f9a455b3000-7f9a457b2000 ---p 00007000 fc:01 1581082                    /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
7f9a457b2000-7f9a457b3000 r--p 00006000 fc:01 1581082                    /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
7f9a457b3000-7f9a457b4000 rw-p 00007000 fc:01 1581082                    /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
7f9a457b4000-7f9a457b7000 r-xp 00000000 fc:01 1573258                    /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0.4800.2
7f9a457b7000-7f9a459b6000 ---p 00003000 fc:01 1573258                    /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0.4800.2
7f9a459b6000-7f9a459b7000 r--p 00002000 fc:01 1573258                    /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0.4800.2
7f9a459b7000-7f9a459b8000 rw-p 00003000 fc:01 1573258                    /usr/lib/x86_64-linux-gnu/libgmodule-2.0.so.0.4800.2
7f9a459b8000-7f9a459bf000 r-xp 00000000 fc:01 31748898                   /lib/x86_64-linux-gnu/librt-2.23.so
7f9a459bf000-7f9a45bbe000 ---p 00007000 fc:01 31748898                   /lib/x86_64-linux-gnu/librt-2.23.so
7f9a45bbe000-7f9a45bbf000 r--p 00006000 fc:01 31748898                   /lib/x86_64-linux-gnu/librt-2.23.so
7f9a45bbf000-7f9a45bc0000 rw-p 00007000 fc:01 31748898                   /lib/x86_64-linux-gnu/librt-2.23.so
7f9a45bc0000-7f9a45dda000 r-xp 00000000 fc:01 31731684                   /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
7f9a45dda000-7f9a45fd9000 ---p 0021a000 fc:01 31731684                   /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
7f9a45fd9000-7f9a45ff5000 r--p 00219000 fc:01 31731684                   /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
7f9a45ff5000-7f9a46001000 rw-p 00235000 fc:01 31731684                   /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
7f9a46001000-7f9a46004000 rw-p 00000000 00:00 0
7f9a46004000-7f9a46013000 r-xp 00000000 fc:01 31723819                   /lib/x86_64-linux-gnu/libbz2.so.1.0.4
7f9a46013000-7f9a46212000 ---p 0000f000 fc:01 31723819                   /lib/x86_64-linux-gnu/libbz2.so.1.0.4
7f9a46212000-7f9a46213000 r--p 0000e000 fc:01 31723819                   /lib/x86_64-linux-gnu/libbz2.so.1.0.4
7f9a46213000-7f9a46214000 rw-p 0000f000 fc:01 31723819                   /lib/x86_64-linux-gnu/libbz2.so.1.0.4
7f9a46214000-7f9a46337000 r-xp 00000000 fc:01 1573257                    /usr/lib/x86_64-linux-gnu/libgnutls.so.30.6.2
7f9a46337000-7f9a46536000 ---p 00123000 fc:01 1573257                    /usr/lib/x86_64-linux-gnu/libgnutls.so.30.6.2
7f9a46536000-7f9a46541000 r--p 00122000 fc:01 1573257                    /usr/lib/x86_64-linux-gnu/libgnutls.so.30.6.2
7f9a46541000-7f9a46543000 rw-p 0012d000 fc:01 1573257                    /usr/lib/x86_64-linux-gnu/libgnutls.so.30.6.2
7f9a46543000-7f9a46544000 rw-p 00000000 00:00 0
7f9a46544000-7f9a4658b000 r-xp 00000000 fc:01 1583240                    /usr/lib/x86_64-linux-gnu/libbluray.so.1.9.2
7f9a4658b000-7f9a4678a000 ---p 00047000 fc:01 1583240                    /usr/lib/x86_64-linux-gnu/libbluray.so.1.9.2
7f9a4678a000-7f9a4678c000 r--p 00046000 fc:01 1583240                    /usr/lib/x86_64-linux-gnu/libbluray.so.1.9.2
7f9a4678c000-7f9a4678d000 rw-p 00048000 fc:01 1583240                    /usr/lib/x86_64-linux-gnu/libbluray.so.1.9.2
7f9a4678d000-7f9a467d7000 r-xp 00000000 fc:01 1583242                    /usr/lib/x86_64-linux-gnu/libgme.so.0.6.0
7f9a467d7000-7f9a469d7000 ---p 0004a000 fc:01 1583242                    /usr/lib/x86_64-linux-gnu/libgme.so.0.6.0
7f9a469d7000-7f9a469da000 r--p 0004a000 fc:01 1583242                    /usr/lib/x86_64-linux-gnu/libgme.so.0.6.0
7f9a469da000-7f9a469db000 rw-p 0004d000 fc:01 1583242                    /usr/lib/x86_64-linux-gnu/libgme.so.0.6.0
7f9a469db000-7f9a46a25000 r-xp 00000000 fc:01 1583244                    /usr/lib/x86_64-linux-gnu/libmodplug.so.1.0.0
7f9a46a25000-7f9a46c25000 ---p 0004a000 fc:01 1583244                    /usr/lib/x86_64-linux-gnu/libmodplug.so.1.0.0
7f9a46c25000-7f9a46c26000 r--p 0004a000 fc:01 1583244                    /usr/lib/x86_64-linux-gnu/libmodplug.so.1.0.0
7f9a46c26000-7f9a46c27000 rw-p 0004b000 fc:01 1583244                    /usr/lib/x86_64-linux-gnu/libmodplug.so.1.0.0
7f9a46c27000-7f9a46d66000 rw-p 00000000 00:00 0
7f9a46d66000-7f9a46d81000 r-xp 00000000 fc:01 1575384                    /usr/lib/x86_64-linux-gnu/librtmp.so.1
7f9a46d81000-7f9a46f80000 ---p 0001b000 fc:01 1575384                    /usr/lib/x86_64-linux-gnu/librtmp.so.1
7f9a46f80000-7f9a46f81000 r--p 0001a000 fc:01 1575384                    /usr/lib/x86_64-linux-gnu/librtmp.so.1
7f9a46f81000-7f9a46f82000 rw-p 0001b000 fc:01 1575384                    /usr/lib/x86_64-linux-gnu/librtmp.so.1
7f9a46f82000-7f9a46fca000 r-xp 00000000 fc:01 1583246                    /usr/lib/x86_64-linux-gnu/libssh-gcrypt.so.4.4.1
7f9a46fca000-7f9a471c9000 ---p 00048000 fc:01 1583246                    /usr/lib/x86_64-linux-gnu/libssh-gcrypt.so.4.4.1
7f9a471c9000-7f9a471ca000 r--p 00047000 fc:01 1583246                    /usr/lib/x86_64-linux-gnu/libssh-gcrypt.so.4.4.1
7f9a471ca000-7f9a471cb000 rw-p 00048000 fc:01 1583246                    /usr/lib/x86_64-linux-gnu/libssh-gcrypt.so.4.4.1
7f9a471cb000-7f9a471ce000 r-xp 00000000 fc:01 31748882                   /lib/x86_64-linux-gnu/libdl-2.23.so
7f9a471ce000-7f9a473cd000 ---p 00003000 fc:01 31748882                   /lib/x86_64-linux-gnu/libdl-2.23.so
7f9a473cd000-7f9a473ce000 r--p 00002000 fc:01 31748882                   /lib/x86_64-linux-gnu/libdl-2.23.so
7f9a473ce000-7f9a473cf000 rw-p 00003000 fc:01 31748882                   /lib/x86_64-linux-gnu/libdl-2.23.so
7f9a473cf000-7f9a473db000 r-xp 00000000 fc:01 1581397                    /usr/lib/x86_64-linux-gnu/libiec61883.so.0.1.1
7f9a473db000-7f9a475da000 ---p 0000c000 fc:01 1581397                    /usr/lib/x86_64-linux-gnu/libiec61883.so.0.1.1
7f9a475da000-7f9a475db000 r--p 0000b000 fc:01 1581397                    /usr/lib/x86_64-linux-gnu/libiec61883.so.0.1.1
7f9a475db000-7f9a475dc000 rw-p 0000c000 fc:01 1581397                    /usr/lib/x86_64-linux-gnu/libiec61883.so.0.1.1
7f9a475dc000-7f9a475df000 r-xp 00000000 fc:01 1581746                    /usr/lib/x86_64-linux-gnu/librom1394.so.0.3.0
7f9a475df000-7f9a477df000 ---p 00003000 fc:01 1581746                    /usr/lib/x86_64-linux-gnu/librom1394.so.0.3.0
7f9a477df000-7f9a477e0000 r--p 00003000 fc:01 1581746                    /usr/lib/x86_64-linux-gnu/librom1394.so.0.3.0
7f9a477e0000-7f9a477e1000 rw-p 00004000 fc:01 1581746                    /usr/lib/x86_64-linux-gnu/librom1394.so.0.3.0
7f9a477e1000-7f9a477e5000 r-xp 00000000 fc:01 1580825                    /usr/lib/x86_64-linux-gnu/libavc1394.so.0.3.0
7f9a477e5000-7f9a479e4000 ---p 00004000 fc:01 1580825                    /usr/lib/x86_64-linux-gnu/libavc1394.so.0.3.0
7f9a479e4000-7f9a479e5000 r--p 00003000 fc:01 1580825                    /usr/lib/x86_64-linux-gnu/libavc1394.so.0.3.0
7f9a479e5000-7f9a479e6000 rw-p 00004000 fc:01 1580825                    /usr/lib/x86_64-linux-gnu/libavc1394.so.0.3.0
7f9a479e6000-7f9a479f3000 r-xp 00000000 fc:01 1581724                    /usr/lib/x86_64-linux-gnu/libraw1394.so.11.1.0
7f9a479f3000-7f9a47bf3000 ---p 0000d000 fc:01 1581724                    /usr/lib/x86_64-linux-gnu/libraw1394.so.11.1.0
7f9a47bf3000-7f9a47bf4000 r--p 0000d000 fc:01 1581724                    /usr/lib/x86_64-linux-gnu/libraw1394.so.11.1.0
7f9a47bf4000-7f9a47bf5000 rw-p 0000e000 fc:01 1581724                    /usr/lib/x86_64-linux-gnu/libraw1394.so.11.1.0
7f9a47bf5000-7f9a47cbc000 r-xp 00000000 fc:01 1580856                    /usr/lib/x86_64-linux-gnu/libcaca.so.0.99.19
7f9a47cbc000-7f9a47ebb000 ---p 000c7000 fc:01 1580856                    /usr/lib/x86_64-linux-gnu/libcaca.so.0.99.19
7f9a47ebb000-7f9a47ebc000 r--p 000c6000 fc:01 1580856                    /usr/lib/x86_64-linux-gnu/libcaca.so.0.99.19
7f9a47ebc000-7f9a47ebd000 rw-p 000c7000 fc:01 1580856                    /usr/lib/x86_64-linux-gnu/libcaca.so.0.99.19
7f9a47ebd000-7f9a47ebe000 rw-p 00000000 00:00 0
7f9a47ebe000-7f9a47f0c000 r-xp 00000000 fc:01 1575349                    /usr/lib/x86_64-linux-gnu/libpulse.so.0.19.0
7f9a47f0c000-7f9a4810c000 ---p 0004e000 fc:01 1575349                    /usr/lib/x86_64-linux-gnu/libpulse.so.0.19.0
7f9a4810c000-7f9a4810d000 r--p 0004e000 fc:01 1575349                    /usr/lib/x86_64-linux-gnu/libpulse.so.0.19.0
7f9a4810d000-7f9a4810e000 rw-p 0004f000 fc:01 1575349                    /usr/lib/x86_64-linux-gnu/libpulse.so.0.19.0
7f9a4810e000-7f9a481d9000 r-xp 00000000 fc:01 1621276                    /usr/lib/nvidia-384/libGL.so.384.111
7f9a481d9000-7f9a4820d000 rwxp 000cb000 fc:01 1621276                    /usr/lib/nvidia-384/libGL.so.384.111
7f9a4820d000-7f9a48221000 r-xp 000ff000 fc:01 1621276                    /usr/lib/nvidia-384/libGL.so.384.111
7f9a48221000-7f9a48420000 ---p 00113000 fc:01 1621276                    /usr/lib/nvidia-384/libGL.so.384.111
7f9a48420000-7f9a48449000 rw-p 00112000 fc:01 1621276                    /usr/lib/nvidia-384/libGL.so.384.111
7f9a48449000-7f9a48450000 rw-p 00000000 00:00 0
7f9a48450000-7f9a48485000 r-xp 00000000 fc:01 1583299                    /usr/lib/x86_64-linux-gnu/libdc1394.so.22.1.11
7f9a48485000-7f9a48684000 ---p 00035000 fc:01 1583299                    /usr/lib/x86_64-linux-gnu/libdc1394.so.22.1.11
7f9a48684000-7f9a48685000 r--p 00034000 fc:01 1583299                    /usr/lib/x86_64-linux-gnu/libdc1394.so.22.1.11
7f9a48685000-7f9a48686000 rw-p 00035000 fc:01 1583299                    /usr/lib/x86_64-linux-gnu/libdc1394.so.22.1.11
7f9a48686000-7f9a486c6000 rw-p 00000000 00:00 0
7f9a486c6000-7f9a4872f000 r-xp 00000000 fc:01 1576139                    /usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0.11.4
7f9a4872f000-7f9a4892f000 ---p 00069000 fc:01 1576139                    /usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0.11.4
7f9a4892f000-7f9a48930000 r--p 00069000 fc:01 1576139                    /usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0.11.4
7f9a48930000-7f9a48931000 rw-p 0006a000 fc:01 1576139                    /usr/lib/x86_64-linux-gnu/libSDL-1.2.so.0.11.4
7f9a48931000-7f9a4895f000 rw-p 00000000 00:00 0
7f9a4895f000-7f9a48a58000 r-xp 00000000 fc:01 1580791                    /usr/lib/x86_64-linux-gnu/libasound.so.2.0.0
7f9a48a58000-7f9a48c57000 ---p 000f9000 fc:01 1580791                    /usr/lib/x86_64-linux-gnu/libasound.so.2.0.0
7f9a48c57000-7f9a48c5e000 r--p 000f8000 fc:01 1580791                    /usr/lib/x86_64-linux-gnu/libasound.so.2.0.0
7f9a48c5e000-7f9a48c5f000 rw-p 000ff000 fc:01 1580791                    /usr/lib/x86_64-linux-gnu/libasound.so.2.0.0
7f9a48c5f000-7f9a48ca5000 r-xp 00000000 fc:01 1581422                    /usr/lib/x86_64-linux-gnu/libjack.so.0.1.0
7f9a48ca5000-7f9a48ea5000 ---p 00046000 fc:01 1581422                    /usr/lib/x86_64-linux-gnu/libjack.so.0.1.0
7f9a48ea5000-7f9a48ea7000 r--p 00046000 fc:01 1581422                    /usr/lib/x86_64-linux-gnu/libjack.so.0.1.0
7f9a48ea7000-7f9a48ea8000 rw-p 00048000 fc:01 1581422                    /usr/lib/x86_64-linux-gnu/libjack.so.0.1.0
7f9a48ea8000-7f9a48eaf000 r-xp 00000000 fc:01 1580882                    /usr/lib/x86_64-linux-gnu/libcdio_cdda.so.1.0.0
7f9a48eaf000-7f9a490ae000 ---p 00007000 fc:01 1580882                    /usr/lib/x86_64-linux-gnu/libcdio_cdda.so.1.0.0
7f9a490ae000-7f9a490af000 r--p 00006000 fc:01 1580882                    /usr/lib/x86_64-linux-gnu/libcdio_cdda.so.1.0.0
7f9a490af000-7f9a490b0000 rw-p 00007000 fc:01 1580882                    /usr/lib/x86_64-linux-gnu/libcdio_cdda.so.1.0.0
7f9a490b0000-7f9a490b7000 r-xp 00000000 fc:01 1580884                    /usr/lib/x86_64-linux-gnu/libcdio_paranoia.so.1.0.0
7f9a490b7000-7f9a492b6000 ---p 00007000 fc:01 1580884                    /usr/lib/x86_64-linux-gnu/libcdio_paranoia.so.1.0.0
7f9a492b6000-7f9a492b7000 r--p 00006000 fc:01 1580884                    /usr/lib/x86_64-linux-gnu/libcdio_paranoia.so.1.0.0
7f9a492b7000-7f9a492b8000 rw-p 00007000 fc:01 1580884                    /usr/lib/x86_64-linux-gnu/libcdio_paranoia.so.1.0.0
7f9a492b8000-7f9a492bb000 r-xp 00000000 fc:01 1582065                    /usr/lib/x86_64-linux-gnu/libxcb-shape.so.0.0.0
7f9a492bb000-7f9a494ba000 ---p 00003000 fc:01 1582065                    /usr/lib/x86_64-linux-gnu/libxcb-shape.so.0.0.0
7f9a494ba000-7f9a494bb000 r--p 00002000 fc:01 1582065                    /usr/lib/x86_64-linux-gnu/libxcb-shape.so.0.0.0
7f9a494bb000-7f9a494bc000 rw-p 00003000 fc:01 1582065                    /usr/lib/x86_64-linux-gnu/libxcb-shape.so.0.0.0
7f9a494bc000-7f9a494c2000 r-xp 00000000 fc:01 1582073                    /usr/lib/x86_64-linux-gnu/libxcb-xfixes.so.0.0.0
7f9a494c2000-7f9a496c2000 ---p 00006000 fc:01 1582073                    /usr/lib/x86_64-linux-gnu/libxcb-xfixes.so.0.0.0
7f9a496c2000-7f9a496c3000 r--p 00006000 fc:01 1582073                    /usr/lib/x86_64-linux-gnu/libxcb-xfixes.so.0.0.0
7f9a496c3000-7f9a496c4000 rw-p 00007000 fc:01 1582073                    /usr/lib/x86_64-linux-gnu/libxcb-xfixes.so.0.0.0
7f9a496c4000-7f9a496c6000 r-xp 00000000 fc:01 1582067                    /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0.0.0
7f9a496c6000-7f9a498c6000 ---p 00002000 fc:01 1582067                    /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0.0.0
7f9a498c6000-7f9a498c7000 r--p 00002000 fc:01 1582067                    /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0.0.0
7f9a498c7000-7f9a498c8000 rw-p 00003000 fc:01 1582067                    /usr/lib/x86_64-linux-gnu/libxcb-shm.so.0.0.0
7f9a498c8000-7f9a498e9000 r-xp 00000000 fc:01 1582077                    /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
7f9a498e9000-7f9a49ae8000 ---p 00021000 fc:01 1582077                    /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
7f9a49ae8000-7f9a49ae9000 r--p 00020000 fc:01 1582077                    /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
7f9a49ae9000-7f9a49aea000 rw-p 00021000 fc:01 1582077                    /usr/lib/x86_64-linux-gnu/libxcb.so.1.1.0
7f9a49aea000-7f9a49afb000 r-xp 00000000 fc:01 1580712                    /usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
7f9a49afb000-7f9a49cfa000 ---p 00011000 fc:01 1580712                    /usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
7f9a49cfa000-7f9a49cfb000 r--p 00010000 fc:01 1580712                    /usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
7f9a49cfb000-7f9a49cfc000 rw-p 00011000 fc:01 1580712                    /usr/lib/x86_64-linux-gnu/libXext.so.6.4.0
7f9a49cfc000-7f9a49d00000 r-xp 00000000 fc:01 1580740                    /usr/lib/x86_64-linux-gnu/libXv.so.1.0.0
7f9a49d00000-7f9a49eff000 ---p 00004000 fc:01 1580740                    /usr/lib/x86_64-linux-gnu/libXv.so.1.0.0
7f9a49eff000-7f9a49f00000 r--p 00003000 fc:01 1580740                    /usr/lib/x86_64-linux-gnu/libXv.so.1.0.0
7f9a49f00000-7f9a49f01000 rw-p 00004000 fc:01 1580740                    /usr/lib/x86_64-linux-gnu/libXv.so.1.0.0
7f9a49f01000-7f9a4a060000 r-xp 00000000 fc:01 1583297                    /usr/lib/x86_64-linux-gnu/libavfilter-ffmpeg.so.5.40.101
7f9a4a060000-7f9a4a25f000 ---p 0015f000 fc:01 1583297                    /usr/lib/x86_64-linux-gnu/libavfilter-ffmpeg.so.5.40.101
7f9a4a25f000-7f9a4a29c000 r--p 0015e000 fc:01 1583297                    /usr/lib/x86_64-linux-gnu/libavfilter-ffmpeg.so.5.40.101
7f9a4a29c000-7f9a4a2a4000 rw-p 0019b000 fc:01 1583297                    /usr/lib/x86_64-linux-gnu/libavfilter-ffmpeg.so.5.40.101
7f9a4a2a4000-7f9a4a2c5000 r-xp 00000000 fc:01 31723887                   /lib/x86_64-linux-gnu/liblzma.so.5.0.0
7f9a4a2c5000-7f9a4a4c4000 ---p 00021000 fc:01 31723887                   /lib/x86_64-linux-gnu/liblzma.so.5.0.0
7f9a4a4c4000-7f9a4a4c5000 r--p 00020000 fc:01 31723887                   /lib/x86_64-linux-gnu/liblzma.so.5.0.0
7f9a4a4c5000-7f9a4a4c6000 rw-p 00021000 fc:01 31723887                   /lib/x86_64-linux-gnu/liblzma.so.5.0.0
7f9a4a4c6000-7f9a4a4e0000 r-xp 00000000 fc:01 1583196                    /usr/lib/x86_64-linux-gnu/libcrystalhd.so.3.6
7f9a4a4e0000-7f9a4a6df000 ---p 0001a000 fc:01 1583196                    /usr/lib/x86_64-linux-gnu/libcrystalhd.so.3.6
7f9a4a6df000-7f9a4a6e0000 r--p 00019000 fc:01 1583196                    /usr/lib/x86_64-linux-gnu/libcrystalhd.so.3.6
7f9a4a6e0000-7f9a4a6e1000 rw-p 0001a000 fc:01 1583196                    /usr/lib/x86_64-linux-gnu/libcrystalhd.so.3.6
7f9a4a6e1000-7f9a4a6ee000 r-xp 00000000 fc:01 1583198                    /usr/lib/x86_64-linux-gnu/libgsm.so.1.0.12
7f9a4a6ee000-7f9a4a8ed000 ---p 0000d000 fc:01 1583198                    /usr/lib/x86_64-linux-gnu/libgsm.so.1.0.12
7f9a4a8ed000-7f9a4a8ee000 r--p 0000c000 fc:01 1583198                    /usr/lib/x86_64-linux-gnu/libgsm.so.1.0.12
7f9a4a8ee000-7f9a4a8ef000 rw-p 0000d000 fc:01 1583198                    /usr/lib/x86_64-linux-gnu/libgsm.so.1.0.12
7f9a4a8ef000-7f9a4a934000 r-xp 00000000 fc:01 1583208                    /usr/lib/x86_64-linux-gnu/libmp3lame.so.0.0.0
7f9a4a934000-7f9a4ab34000 ---p 00045000 fc:01 1583208                    /usr/lib/x86_64-linux-gnu/libmp3lame.so.0.0.0
7f9a4ab34000-7f9a4ab35000 r--p 00045000 fc:01 1583208                    /usr/lib/x86_64-linux-gnu/libmp3lame.so.0.0.0
7f9a4ab35000-7f9a4ab36000 rw-p 00046000 fc:01 1583208                    /usr/lib/x86_64-linux-gnu/libmp3lame.so.0.0.0
7f9a4ab36000-7f9a4ab64000 rw-p 00000000 00:00 0
7f9a4ab64000-7f9a4ab86000 r-xp 00000000 fc:01 1583211                    /usr/lib/x86_64-linux-gnu/libopenjpeg.so.1.5.2
7f9a4ab86000-7f9a4ad85000 ---p 00022000 fc:01 1583211                    /usr/lib/x86_64-linux-gnu/libopenjpeg.so.1.5.2
7f9a4ad85000-7f9a4ad86000 r--p 00021000 fc:01 1583211                    /usr/lib/x86_64-linux-gnu/libopenjpeg.so.1.5.2
7f9a4ad86000-7f9a4ad87000 rw-p 00022000 fc:01 1583211                    /usr/lib/x86_64-linux-gnu/libopenjpeg.so.1.5.2
7f9a4ad87000-7f9a4add0000 r-xp 00000000 fc:01 1581610                    /usr/lib/x86_64-linux-gnu/libopus.so.0.5.2
7f9a4add0000-7f9a4afcf000 ---p 00049000 fc:01 1581610                    /usr/lib/x86_64-linux-gnu/libopus.so.0.5.2
7f9a4afcf000-7f9a4afd0000 r--p 00048000 fc:01 1581610                    /usr/lib/x86_64-linux-gnu/libopus.so.0.5.2
7f9a4afd0000-7f9a4afd1000 rw-p 00049000 fc:01 1581610                    /usr/lib/x86_64-linux-gnu/libopus.so.0.5.2
7f9a4afd1000-7f9a4b0a2000 r-xp 00000000 fc:01 1583200                    /usr/lib/x86_64-linux-gnu/libschroedinger-1.0.so.0.11.0
7f9a4b0a2000-7f9a4b2a2000 ---p 000d1000 fc:01 1583200                    /usr/lib/x86_64-linux-gnu/libschroedinger-1.0.so.0.11.0
7f9a4b2a2000-7f9a4b2a4000 r--p 000d1000 fc:01 1583200                    /usr/lib/x86_64-linux-gnu/libschroedinger-1.0.so.0.11.0
7f9a4b2a4000-7f9a4b2a5000 rw-p 000d3000 fc:01 1583200                    /usr/lib/x86_64-linux-gnu/libschroedinger-1.0.so.0.11.0
7f9a4b2a5000-7f9a4b2a6000 rw-p 00000000 00:00 0
7f9a4b2a6000-7f9a4b2b2000 r-xp 00000000 fc:01 1583214                    /usr/lib/x86_64-linux-gnu/libshine.so.3.0.1
7f9a4b2b2000-7f9a4b4b1000 ---p 0000c000 fc:01 1583214                    /usr/lib/x86_64-linux-gnu/libshine.so.3.0.1
7f9a4b4b1000-7f9a4b4b2000 r--p 0000b000 fc:01 1583214                    /usr/lib/x86_64-linux-gnu/libshine.so.3.0.1
7f9a4b4b2000-7f9a4b4b3000 rw-p 0000c000 fc:01 1583214                    /usr/lib/x86_64-linux-gnu/libshine.so.3.0.1
7f9a4b4b3000-7f9a4b4ba000 r-xp 00000000 fc:01 1583216                    /usr/lib/x86_64-linux-gnu/libsnappy.so.1.3.0
7f9a4b4ba000-7f9a4b6b9000 ---p 00007000 fc:01 1583216                    /usr/lib/x86_64-linux-gnu/libsnappy.so.1.3.0
7f9a4b6b9000-7f9a4b6ba000 r--p 00006000 fc:01 1583216                    /usr/lib/x86_64-linux-gnu/libsnappy.so.1.3.0
7f9a4b6ba000-7f9a4b6bb000 rw-p 00007000 fc:01 1583216                    /usr/lib/x86_64-linux-gnu/libsnappy.so.1.3.0
7f9a4b6bb000-7f9a4b6d2000 r-xp 00000000 fc:01 1581822                    /usr/lib/x86_64-linux-gnu/libspeex.so.1.5.0
7f9a4b6d2000-7f9a4b8d2000 ---p 00017000 fc:01 1581822                    /usr/lib/x86_64-linux-gnu/libspeex.so.1.5.0
7f9a4b8d2000-7f9a4b8d3000 r--p 00017000 fc:01 1581822                    /usr/lib/x86_64-linux-gnu/libspeex.so.1.5.0
7f9a4b8d3000-7f9a4b8d4000 rw-p 00018000 fc:01 1581822                    /usr/lib/x86_64-linux-gnu/libspeex.so.1.5.0
7f9a4b8d4000-7f9a4b8ed000 r-xp 00000000 fc:01 1581859                    /usr/lib/x86_64-linux-gnu/libtheoradec.so.1.1.4
7f9a4b8ed000-7f9a4baec000 ---p 00019000 fc:01 1581859                    /usr/lib/x86_64-linux-gnu/libtheoradec.so.1.1.4
7f9a4baec000-7f9a4baed000 r--p 00018000 fc:01 1581859                    /usr/lib/x86_64-linux-gnu/libtheoradec.so.1.1.4
7f9a4baed000-7f9a4baee000 rw-p 00019000 fc:01 1581859                    /usr/lib/x86_64-linux-gnu/libtheoradec.so.1.1.4
7f9a4baee000-7f9a4bb2c000 r-xp 00000000 fc:01 1581861                    /usr/lib/x86_64-linux-gnu/libtheoraenc.so.1.1.2
7f9a4bb2c000-7f9a4bd2b000 ---p 0003e000 fc:01 1581861                    /usr/lib/x86_64-linux-gnu/libtheoraenc.so.1.1.2
7f9a4bd2b000-7f9a4bd2c000 r--p 0003d000 fc:01 1581861                    /usr/lib/x86_64-linux-gnu/libtheoraenc.so.1.1.2
7f9a4bd2c000-7f9a4bd2d000 rw-p 0003e000 fc:01 1581861                    /usr/lib/x86_64-linux-gnu/libtheoraenc.so.1.1.2
7f9a4bd2d000-7f9a4bd4b000 r-xp 00000000 fc:01 1583222                    /usr/lib/x86_64-linux-gnu/libtwolame.so.0.0.0
7f9a4bd4b000-7f9a4bf4a000 ---p 0001e000 fc:01 1583222                    /usr/lib/x86_64-linux-gnu/libtwolame.so.0.0.0
7f9a4bf4a000-7f9a4bf4b000 r--p 0001d000 fc:01 1583222                    /usr/lib/x86_64-linux-gnu/libtwolame.so.0.0.0
7f9a4bf4b000-7f9a4bf4c000 rw-p 0001e000 fc:01 1583222                    /usr/lib/x86_64-linux-gnu/libtwolame.so.0.0.0
7f9a4bf4c000-7f9a4bf50000 rw-p 00000000 00:00 0
7f9a4bf50000-7f9a4bf7a000 r-xp 00000000 fc:01 1578174                    /usr/lib/x86_64-linux-gnu/libvorbis.so.0.4.8
7f9a4bf7a000-7f9a4c17a000 ---p 0002a000 fc:01 1578174                    /usr/lib/x86_64-linux-gnu/libvorbis.so.0.4.8
7f9a4c17a000-7f9a4c17b000 r--p 0002a000 fc:01 1578174                    /usr/lib/x86_64-linux-gnu/libvorbis.so.0.4.8
7f9a4c17b000-7f9a4c17c000 rw-p 0002b000 fc:01 1578174                    /usr/lib/x86_64-linux-gnu/libvorbis.so.0.4.8
7f9a4c17c000-7f9a4c209000 r-xp 00000000 fc:01 1578172                    /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2.0.11
7f9a4c209000-7f9a4c408000 ---p 0008d000 fc:01 1578172                    /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2.0.11
7f9a4c408000-7f9a4c424000 r--p 0008c000 fc:01 1578172                    /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2.0.11
7f9a4c424000-7f9a4c425000 rw-p 000a8000 fc:01 1578172                    /usr/lib/x86_64-linux-gnu/libvorbisenc.so.2.0.11
7f9a4c425000-7f9a4c644000 r-xp 00000000 fc:01 1581961                    /usr/lib/x86_64-linux-gnu/libvpx.so.3.0.0
7f9a4c644000-7f9a4c843000 ---p 0021f000 fc:01 1581961                    /usr/lib/x86_64-linux-gnu/libvpx.so.3.0.0
7f9a4c843000-7f9a4c845000 r--p 0021e000 fc:01 1581961                    /usr/lib/x86_64-linux-gnu/libvpx.so.3.0.0
7f9a4c845000-7f9a4c846000 rw-p 00220000 fc:01 1581961                    /usr/lib/x86_64-linux-gnu/libvpx.so.3.0.0
7f9a4c846000-7f9a4c849000 rw-p 00000000 00:00 0
7f9a4c849000-7f9a4c871000 r-xp 00000000 fc:01 1576895                    /usr/lib/x86_64-linux-gnu/libwavpack.so.1.1.7
7f9a4c871000-7f9a4ca70000 ---p 00028000 fc:01 1576895                    /usr/lib/x86_64-linux-gnu/libwavpack.so.1.1.7
7f9a4ca70000-7f9a4ca71000 r--p 00027000 fc:01 1576895                    /usr/lib/x86_64-linux-gnu/libwavpack.so.1.1.7
7f9a4ca71000-7f9a4ca72000 rw-p 00028000 fc:01 1576895                    /usr/lib/x86_64-linux-gnu/libwavpack.so.1.1.7
7f9a4ca72000-7f9a4cacb000 r-xp 00000000 fc:01 1581981                    /usr/lib/x86_64-linux-gnu/libwebp.so.5.0.4
7f9a4cacb000-7f9a4cccb000 ---p 00059000 fc:01 1581981                    /usr/lib/x86_64-linux-gnu/libwebp.so.5.0.4
7f9a4cccb000-7f9a4cccc000 r--p 00059000 fc:01 1581981                    /usr/lib/x86_64-linux-gnu/libwebp.so.5.0.4
7f9a4cccc000-7f9a4ccce000 rw-p 0005a000 fc:01 1581981                    /usr/lib/x86_64-linux-gnu/libwebp.so.5.0.4
7f9a4ccce000-7f9a4cdf6000 r-xp 00000000 fc:01 1583228                    /usr/lib/x86_64-linux-gnu/libx264.so.148
7f9a4cdf6000-7f9a4cff5000 ---p 00128000 fc:01 1583228                    /usr/lib/x86_64-linux-gnu/libx264.so.148
7f9a4cff5000-7f9a4cff6000 r--p 00127000 fc:01 1583228                    /usr/lib/x86_64-linux-gnu/libx264.so.148
7f9a4cff6000-7f9a4cff7000 rw-p 00128000 fc:01 1583228                    /usr/lib/x86_64-linux-gnu/libx264.so.148
7f9a4cff7000-7f9a4d072000 rw-p 00000000 00:00 0
7f9a4d072000-7f9a4da7f000 r-xp 00000000 fc:01 1583229                    /usr/lib/x86_64-linux-gnu/libx265.so.79
7f9a4da7f000-7f9a4dc7e000 ---p 00a0d000 fc:01 1583229                    /usr/lib/x86_64-linux-gnu/libx265.so.79
7f9a4dc7e000-7f9a4dc81000 r--p 00a0c000 fc:01 1583229                    /usr/lib/x86_64-linux-gnu/libx265.so.79
7f9a4dc81000-7f9a4dc84000 rw-p 00a0f000 fc:01 1583229                    /usr/lib/x86_64-linux-gnu/libx265.so.79
7f9a4dc84000-7f9a4dc91000 rw-p 00000000 00:00 0
7f9a4dc91000-7f9a4dd32000 r-xp 00000000 fc:01 1583230                    /usr/lib/x86_64-linux-gnu/libxvidcore.so.4.3
7f9a4dd32000-7f9a4df31000 ---p 000a1000 fc:01 1583230                    /usr/lib/x86_64-linux-gnu/libxvidcore.so.4.3
7f9a4df31000-7f9a4df32000 r--p 000a0000 fc:01 1583230                    /usr/lib/x86_64-linux-gnu/libxvidcore.so.4.3
7f9a4df32000-7f9a4df3c000 rw-p 000a1000 fc:01 1583230                    /usr/lib/x86_64-linux-gnu/libxvidcore.so.4.3
7f9a4df3c000-7f9a4dfa5000 rw-p 00000000 00:00 0
7f9a4dfa5000-7f9a4e01c000 r-xp 00000000 fc:01 1583232                    /usr/lib/x86_64-linux-gnu/libzvbi.so.0.13.2
7f9a4e01c000-7f9a4e21b000 ---p 00077000 fc:01 1583232                    /usr/lib/x86_64-linux-gnu/libzvbi.so.0.13.2
7f9a4e21b000-7f9a4e224000 r--p 00076000 fc:01 1583232                    /usr/lib/x86_64-linux-gnu/libzvbi.so.0.13.2
7f9a4e224000-7f9a4e230000 rw-p 0007f000 fc:01 1583232                    /usr/lib/x86_64-linux-gnu/libzvbi.so.0.13.2
7f9a4e230000-7f9a4e24b000 r-xp 00000000 fc:01 1575114                    /usr/lib/x86_64-linux-gnu/libva.so.1.3900.0
7f9a4e24b000-7f9a4e44a000 ---p 0001b000 fc:01 1575114                    /usr/lib/x86_64-linux-gnu/libva.so.1.3900.0
7f9a4e44a000-7f9a4e44b000 r--p 0001a000 fc:01 1575114                    /usr/lib/x86_64-linux-gnu/libva.so.1.3900.0
7f9a4e44b000-7f9a4e44c000 rw-p 0001b000 fc:01 1575114                    /usr/lib/x86_64-linux-gnu/libva.so.1.3900.0
7f9a4e44c000-7f9a4e466000 r-xp 00000000 fc:01 1583220                    /usr/lib/x86_64-linux-gnu/libswresample-ffmpeg.so.1.2.101
7f9a4e466000-7f9a4e666000 ---p 0001a000 fc:01 1583220                    /usr/lib/x86_64-linux-gnu/libswresample-ffmpeg.so.1.2.101
7f9a4e666000-7f9a4e668000 r--p 0001a000 fc:01 1583220                    /usr/lib/x86_64-linux-gnu/libswresample-ffmpeg.so.1.2.101
7f9a4e668000-7f9a4e669000 rw-p 0001c000 fc:01 1583220                    /usr/lib/x86_64-linux-gnu/libswresample-ffmpeg.so.1.2.101
7f9a4e669000-7f9a4e688000 r-xp 00000000 fc:01 1581685                    /usr/lib/x86_64-linux-gnu/libproxy.so.1.0.0
7f9a4e688000-7f9a4e888000 ---p 0001f000 fc:01 1581685                    /usr/lib/x86_64-linux-gnu/libproxy.so.1.0.0
7f9a4e888000-7f9a4e889000 r--p 0001f000 fc:01 1581685                    /usr/lib/x86_64-linux-gnu/libproxy.so.1.0.0
7f9a4e889000-7f9a4e88a000 rw-p 00020000 fc:01 1581685                    /usr/lib/x86_64-linux-gnu/libproxy.so.1.0.0
7f9a4e88a000-7f9a4e8a3000 r-xp 00000000 fc:01 31720075                   /lib/x86_64-linux-gnu/libz.so.1.2.8
7f9a4e8a3000-7f9a4eaa2000 ---p 00019000 fc:01 31720075                   /lib/x86_64-linux-gnu/libz.so.1.2.8
7f9a4eaa2000-7f9a4eaa3000 r--p 00018000 fc:01 31720075                   /lib/x86_64-linux-gnu/libz.so.1.2.8
7f9a4eaa3000-7f9a4eaa4000 rw-p 00019000 fc:01 31720075                   /lib/x86_64-linux-gnu/libz.so.1.2.8
7f9a4eaa4000-7f9a4ec64000 r-xp 00000000 fc:01 31748880                   /lib/x86_64-linux-gnu/libc-2.23.so
7f9a4ec64000-7f9a4ee64000 ---p 001c0000 fc:01 31748880                   /lib/x86_64-linux-gnu/libc-2.23.so
7f9a4ee64000-7f9a4ee68000 r--p 001c0000 fc:01 31748880                   /lib/x86_64-linux-gnu/libc-2.23.so
7f9a4ee68000-7f9a4ee6a000 rw-p 001c4000 fc:01 31748880                   /lib/x86_64-linux-gnu/libc-2.23.so
7f9a4ee6a000-7f9a4ee6e000 rw-p 00000000 00:00 0
7f9a4ee6e000-7f9a4efe0000 r-xp 00000000 fc:01 1572893                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7f9a4efe0000-7f9a4f1e0000 ---p 00172000 fc:01 1572893                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7f9a4f1e0000-7f9a4f1ea000 r--p 00172000 fc:01 1572893                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7f9a4f1ea000-7f9a4f1ec000 rw-p 0017c000 fc:01 1572893                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7f9a4f1ec000-7f9a4f1f0000 rw-p 00000000 00:00 0
7f9a4f1f0000-7f9a4f6b5000 r-xp 00000000 fc:01 1579423                    /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.5.1
7f9a4f6b5000-7f9a4f6c1000 r--p 004c4000 fc:01 1579423                    /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.5.1
7f9a4f6c1000-7f9a4f6c2000 rw-p 004d0000 fc:01 1579423                    /usr/lib/x86_64-linux-gnu/libQt5Core.so.5.5.1
7f9a4f6c2000-7f9a4f6c6000 rw-p 00000000 00:00 0
7f9a4f6c6000-7f9a4fbed000 r-xp 00000000 fc:01 1579443                    /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5.5.1
7f9a4fbed000-7f9a4fbee000 ---p 00527000 fc:01 1579443                    /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5.5.1
7f9a4fbee000-7f9a4fc03000 r--p 00527000 fc:01 1579443                    /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5.5.1
7f9a4fc03000-7f9a4fc09000 rw-p 0053c000 fc:01 1579443                    /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5.5.1
7f9a4fc09000-7f9a4fc0e000 rw-p 00000000 00:00 0
7f9a4fc0e000-7f9a4fc59000 r-xp 00000000 fc:01 2116803                    /usr/local/lib/libfilteraudio.so.0.0.0
7f9a4fc59000-7f9a4fe58000 ---p 0004b000 fc:01 2116803                    /usr/local/lib/libfilteraudio.so.0.0.0
7f9a4fe58000-7f9a4fe59000 r--p 0004a000 fc:01 2116803                    /usr/local/lib/libfilteraudio.so.0.0.0
7f9a4fe59000-7f9a4fe5a000 rw-p 0004b000 fc:01 2116803                    /usr/local/lib/libfilteraudio.so.0.0.0
7f9a4fe5a000-7f9a4ffda000 r-xp 00000000 fc:01 1573306                    /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.4800.2
7f9a4ffda000-7f9a501da000 ---p 00180000 fc:01 1573306                    /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.4800.2
7f9a501da000-7f9a501de000 r--p 00180000 fc:01 1573306                    /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.4800.2
7f9a501de000-7f9a501e0000 rw-p 00184000 fc:01 1573306                    /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.4800.2
7f9a501e0000-7f9a501e2000 rw-p 00000000 00:00 0
7f9a501e2000-7f9a502f0000 r-xp 00000000 fc:01 1580860                    /usr/lib/x86_64-linux-gnu/libcairo.so.2.11400.6
7f9a502f0000-7f9a504f0000 ---p 0010e000 fc:01 1580860                    /usr/lib/x86_64-linux-gnu/libcairo.so.2.11400.6
7f9a504f0000-7f9a504f3000 r--p 0010e000 fc:01 1580860                    /usr/lib/x86_64-linux-gnu/libcairo.so.2.11400.6
7f9a504f3000-7f9a504f4000 rw-p 00111000 fc:01 1580860                    /usr/lib/x86_64-linux-gnu/libcairo.so.2.11400.6
7f9a504f4000-7f9a504f6000 rw-p 00000000 00:00 0
7f9a504f6000-7f9a505a6000 r-xp 00000000 fc:01 1573035                    /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0.2400.30
7f9a505a6000-7f9a507a5000 ---p 000b0000 fc:01 1573035                    /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0.2400.30
7f9a507a5000-7f9a507a9000 r--p 000af000 fc:01 1573035                    /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0.2400.30
7f9a507a9000-7f9a507ab000 rw-p 000b3000 fc:01 1573035                    /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0.2400.30
7f9a507ab000-7f9a50be9000 r-xp 00000000 fc:01 1580337                    /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0.2400.30
7f9a50be9000-7f9a50de8000 ---p 0043e000 fc:01 1580337                    /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0.2400.30
7f9a50de8000-7f9a50def000 r--p 0043d000 fc:01 1580337                    /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0.2400.30
7f9a50def000-7f9a50df3000 rw-p 00444000 fc:01 1580337                    /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0.2400.30
7f9a50df3000-7f9a50df6000 rw-p 00000000 00:00 0
7f9a50df6000-7f9a50f05000 r-xp 00000000 fc:01 31719452                   /lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.2
7f9a50f05000-7f9a51104000 ---p 0010f000 fc:01 31719452                   /lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.2
7f9a51104000-7f9a51105000 r--p 0010e000 fc:01 31719452                   /lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.2
7f9a51105000-7f9a51106000 rw-p 0010f000 fc:01 31719452                   /lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.2
7f9a51106000-7f9a51107000 rw-p 00000000 00:00 0
7f9a51107000-7f9a51159000 r-xp 00000000 fc:01 1573303                    /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4800.2
7f9a51159000-7f9a51358000 ---p 00052000 fc:01 1573303                    /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4800.2
7f9a51358000-7f9a51359000 r--p 00051000 fc:01 1573303                    /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4800.2
7f9a51359000-7f9a5135a000 rw-p 00052000 fc:01 1573303                    /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.4800.2
7f9a5135a000-7f9a5137b000 r-xp 00000000 fc:01 1573072                    /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0.3200.2
7f9a5137b000-7f9a5157a000 ---p 00021000 fc:01 1573072                    /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0.3200.2
7f9a5157a000-7f9a5157b000 r--p 00020000 fc:01 1573072                    /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0.3200.2
7f9a5157b000-7f9a5157c000 rw-p 00021000 fc:01 1573072                    /usr/lib/x86_64-linux-gnu/libgdk_pixbuf-2.0.so.0.3200.2
7f9a5157c000-7f9a5157e000 r-xp 00000000 fc:01 1580734                    /usr/lib/x86_64-linux-gnu/libXss.so.1.0.0
7f9a5157e000-7f9a5177e000 ---p 00002000 fc:01 1580734                    /usr/lib/x86_64-linux-gnu/libXss.so.1.0.0
7f9a5177e000-7f9a5177f000 r--p 00002000 fc:01 1580734                    /usr/lib/x86_64-linux-gnu/libXss.so.1.0.0
7f9a5177f000-7f9a51780000 rw-p 00003000 fc:01 1580734                    /usr/lib/x86_64-linux-gnu/libXss.so.1.0.0
7f9a51780000-7f9a518b5000 r-xp 00000000 fc:01 1580695                    /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0
7f9a518b5000-7f9a51ab5000 ---p 00135000 fc:01 1580695                    /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0
7f9a51ab5000-7f9a51ab6000 r--p 00135000 fc:01 1580695                    /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0
7f9a51ab6000-7f9a51aba000 rw-p 00136000 fc:01 1580695                    /usr/lib/x86_64-linux-gnu/libX11.so.6.3.0
7f9a51aba000-7f9a51b23000 r-xp 00000000 fc:01 1583202                    /usr/lib/x86_64-linux-gnu/libopenal.so.1.16.0
7f9a51b23000-7f9a51d22000 ---p 00069000 fc:01 1583202                    /usr/lib/x86_64-linux-gnu/libopenal.so.1.16.0
7f9a51d22000-7f9a51d26000 r--p 00068000 fc:01 1583202                    /usr/lib/x86_64-linux-gnu/libopenal.so.1.16.0
7f9a51d26000-7f9a51d27000 rw-p 0006c000 fc:01 1583202                    /usr/lib/x86_64-linux-gnu/libopenal.so.1.16.0
7f9a51d27000-7f9a51d2a000 rw-p 00000000 00:00 0
7f9a51d2a000-7f9a51e32000 r-xp 00000000 fc:01 31748876                   /lib/x86_64-linux-gnu/libm-2.23.so
7f9a51e32000-7f9a52031000 ---p 00108000 fc:01 31748876                   /lib/x86_64-linux-gnu/libm-2.23.so
7f9a52031000-7f9a52032000 r--p 00107000 fc:01 31748876                   /lib/x86_64-linux-gnu/libm-2.23.so
7f9a52032000-7f9a52033000 rw-p 00108000 fc:01 31748876                   /lib/x86_64-linux-gnu/libm-2.23.so
7f9a52033000-7f9a5204b000 r-xp 00000000 fc:01 31748879                   /lib/x86_64-linux-gnu/libpthread-2.23.so
7f9a5204b000-7f9a5224a000 ---p 00018000 fc:01 31748879                   /lib/x86_64-linux-gnu/libpthread-2.23.so
7f9a5224a000-7f9a5224b000 r--p 00017000 fc:01 31748879                   /lib/x86_64-linux-gnu/libpthread-2.23.so
7f9a5224b000-7f9a5224c000 rw-p 00018000 fc:01 31748879                   /lib/x86_64-linux-gnu/libpthread-2.23.so
7f9a5224c000-7f9a52250000 rw-p 00000000 00:00 0
7f9a52250000-7f9a522b1000 r-xp 00000000 fc:01 2104160                    /usr/local/lib/libtoxcore.so.2.1.0
7f9a522b1000-7f9a524b0000 ---p 00061000 fc:01 2104160                    /usr/local/lib/libtoxcore.so.2.1.0
7f9a524b0000-7f9a524b1000 r--p 00060000 fc:01 2104160                    /usr/local/lib/libtoxcore.so.2.1.0
7f9a524b1000-7f9a524b3000 rw-p 00061000 fc:01 2104160                    /usr/local/lib/libtoxcore.so.2.1.0
7f9a524b3000-7f9a52579000 r-xp 00000000 fc:01 1583307                    /usr/lib/x86_64-linux-gnu/libsqlcipher.so.0.8.6
7f9a52579000-7f9a52778000 ---p 000c6000 fc:01 1583307                    /usr/lib/x86_64-linux-gnu/libsqlcipher.so.0.8.6
7f9a52778000-7f9a5277c000 r--p 000c5000 fc:01 1583307                    /usr/lib/x86_64-linux-gnu/libsqlcipher.so.0.8.6
7f9a5277c000-7f9a5277e000 rw-p 000c9000 fc:01 1583307                    /usr/lib/x86_64-linux-gnu/libsqlcipher.so.0.8.6
7f9a5277e000-7f9a5277f000 rw-p 00000000 00:00 0
7f9a5277f000-7f9a52804000 r-xp 00000000 fc:01 1583291                    /usr/lib/x86_64-linux-gnu/libswscale-ffmpeg.so.3.1.101
7f9a52804000-7f9a52a03000 ---p 00085000 fc:01 1583291                    /usr/lib/x86_64-linux-gnu/libswscale-ffmpeg.so.3.1.101
7f9a52a03000-7f9a52a05000 r--p 00084000 fc:01 1583291                    /usr/lib/x86_64-linux-gnu/libswscale-ffmpeg.so.3.1.101
7f9a52a05000-7f9a52a06000 rw-p 00086000 fc:01 1583291                    /usr/lib/x86_64-linux-gnu/libswscale-ffmpeg.so.3.1.101
7f9a52a06000-7f9a52a0e000 rw-p 00000000 00:00 0
7f9a52a0e000-7f9a52a6b000 r-xp 00000000 fc:01 1583293                    /usr/lib/x86_64-linux-gnu/libsodium.so.18.0.1
7f9a52a6b000-7f9a52c6a000 ---p 0005d000 fc:01 1583293                    /usr/lib/x86_64-linux-gnu/libsodium.so.18.0.1
7f9a52c6a000-7f9a52c6b000 r--p 0005c000 fc:01 1583293                    /usr/lib/x86_64-linux-gnu/libsodium.so.18.0.1
7f9a52c6b000-7f9a52c6c000 rw-p 0005d000 fc:01 1583293                    /usr/lib/x86_64-linux-gnu/libsodium.so.18.0.1
7f9a52c6c000-7f9a52c77000 r-xp 00000000 fc:01 1583305                    /usr/lib/x86_64-linux-gnu/libqrencode.so.3.4.4
7f9a52c77000-7f9a52e76000 ---p 0000b000 fc:01 1583305                    /usr/lib/x86_64-linux-gnu/libqrencode.so.3.4.4
7f9a52e76000-7f9a52e77000 r--p 0000a000 fc:01 1583305                    /usr/lib/x86_64-linux-gnu/libqrencode.so.3.4.4
7f9a52e77000-7f9a52e78000 rw-p 0000b000 fc:01 1583305                    /usr/lib/x86_64-linux-gnu/libqrencode.so.3.4.4
7f9a52e78000-7f9a52ea9000 r-xp 00000000 fc:01 1581064                    /usr/lib/x86_64-linux-gnu/libexif.so.12.3.3
7f9a52ea9000-7f9a530a8000 ---p 00031000 fc:01 1581064                    /usr/lib/x86_64-linux-gnu/libexif.so.12.3.3
7f9a530a8000-7f9a530bb000 r--p 00030000 fc:01 1581064                    /usr/lib/x86_64-linux-gnu/libexif.so.12.3.3
7f9a530bb000-7f9a530bc000 rw-p 00043000 fc:01 1581064                    /usr/lib/x86_64-linux-gnu/libexif.so.12.3.3
7f9a530bc000-7f9a53112000 r-xp 00000000 fc:01 1583206                    /usr/lib/x86_64-linux-gnu/libavutil-ffmpeg.so.54.31.100
7f9a53112000-7f9a53311000 ---p 00056000 fc:01 1583206                    /usr/lib/x86_64-linux-gnu/libavutil-ffmpeg.so.54.31.100
7f9a53311000-7f9a53317000 r--p 00055000 fc:01 1583206                    /usr/lib/x86_64-linux-gnu/libavutil-ffmpeg.so.54.31.100
7f9a53317000-7f9a53318000 rw-p 0005b000 fc:01 1583206                    /usr/lib/x86_64-linux-gnu/libavutil-ffmpeg.so.54.31.100
7f9a53318000-7f9a5332b000 rw-p 00000000 00:00 0
7f9a5332b000-7f9a53500000 r-xp 00000000 fc:01 1583250                    /usr/lib/x86_64-linux-gnu/libavformat-ffmpeg.so.56.40.101
7f9a53500000-7f9a53700000 ---p 001d5000 fc:01 1583250                    /usr/lib/x86_64-linux-gnu/libavformat-ffmpeg.so.56.40.101
7f9a53700000-7f9a53714000 r--p 001d5000 fc:01 1583250                    /usr/lib/x86_64-linux-gnu/libavformat-ffmpeg.so.56.40.101
7f9a53714000-7f9a53729000 rw-p 001e9000 fc:01 1583250                    /usr/lib/x86_64-linux-gnu/libavformat-ffmpeg.so.56.40.101
7f9a53729000-7f9a53751000 r-xp 00000000 fc:01 1583301                    /usr/lib/x86_64-linux-gnu/libavdevice-ffmpeg.so.56.4.100
7f9a53751000-7f9a53950000 ---p 00028000 fc:01 1583301                    /usr/lib/x86_64-linux-gnu/libavdevice-ffmpeg.so.56.4.100
7f9a53950000-7f9a53955000 r--p 00027000 fc:01 1583301                    /usr/lib/x86_64-linux-gnu/libavdevice-ffmpeg.so.56.4.100
7f9a53955000-7f9a53957000 rw-p 0002c000 fc:01 1583301                    /usr/lib/x86_64-linux-gnu/libavdevice-ffmpeg.so.56.4.100
7f9a53957000-7f9a54483000 r-xp 00000000 fc:01 1583236                    /usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so.56.60.100
7f9a54483000-7f9a54682000 ---p 00b2c000 fc:01 1583236                    /usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so.56.60.100
7f9a54682000-7f9a546ad000 r--p 00b2b000 fc:01 1583236                    /usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so.56.60.100
7f9a546ad000-7f9a546d0000 rw-p 00b56000 fc:01 1583236                    /usr/lib/x86_64-linux-gnu/libavcodec-ffmpeg.so.56.60.100
7f9a546d0000-7f9a54d83000 rw-p 00000000 00:00 0
7f9a54d83000-7f9a54dbc000 r-xp 00000000 fc:01 1579468                    /usr/lib/x86_64-linux-gnu/libQt5Xml.so.5.5.1
7f9a54dbc000-7f9a54dbe000 r--p 00038000 fc:01 1579468                    /usr/lib/x86_64-linux-gnu/libQt5Xml.so.5.5.1
7f9a54dbe000-7f9a54dbf000 rw-p 0003a000 fc:01 1579468                    /usr/lib/x86_64-linux-gnu/libQt5Xml.so.5.5.1
7f9a54dbf000-7f9a55418000 r-xp 00000000 fc:01 1579447                    /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.5.1
7f9a55418000-7f9a55446000 r--p 00658000 fc:01 1579447                    /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.5.1
7f9a55446000-7f9a5544b000 rw-p 00686000 fc:01 1579447                    /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5.5.1
7f9a5544b000-7f9a5544c000 rw-p 00000000 00:00 0
7f9a5544c000-7f9a5545d000 r-xp 00000000 fc:01 31748878                   /lib/x86_64-linux-gnu/ld-2.23.so
7f9a5545d000-7f9a5545e000 r-xp 00011000 fc:01 31748878                   /lib/x86_64-linux-gnu/ld-2.23.so
7f9a5545e000-7f9a55472000 r-xp 00012000 fc:01 31748878                   /lib/x86_64-linux-gnu/ld-2.23.so
7f9a55472000-7f9a55495000 rw-p 00000000 00:00 0
7f9a55495000-7f9a554e8000 r-xp 00000000 fc:01 1580635                    /usr/lib/x86_64-linux-gnu/libQt5Svg.so.5.5.1
7f9a554e8000-7f9a554ea000 r--p 00052000 fc:01 1580635                    /usr/lib/x86_64-linux-gnu/libQt5Svg.so.5.5.1
7f9a554ea000-7f9a554ec000 rw-p 00054000 fc:01 1580635                    /usr/lib/x86_64-linux-gnu/libQt5Svg.so.5.5.1
7f9a554ec000-7f9a5563d000 r-xp 00000000 fc:01 1579433                    /usr/lib/x86_64-linux-gnu/libQt5Network.so.5.5.1
7f9a5563d000-7f9a5563e000 ---p 00151000 fc:01 1579433                    /usr/lib/x86_64-linux-gnu/libQt5Network.so.5.5.1
7f9a5563e000-7f9a55644000 r--p 00151000 fc:01 1579433                    /usr/lib/x86_64-linux-gnu/libQt5Network.so.5.5.1
7f9a55644000-7f9a55646000 rw-p 00157000 fc:01 1579433                    /usr/lib/x86_64-linux-gnu/libQt5Network.so.5.5.1
7f9a55646000-7f9a55647000 rw-p 00000000 00:00 0
7f9a55647000-7f9a55651000 r-xp 00000000 fc:01 1969796                    /usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so
7f9a55651000-7f9a55652000 r--p 00009000 fc:01 1969796                    /usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so
7f9a55652000-7f9a55653000 rw-p 0000a000 fc:01 1969796                    /usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libcomposeplatforminputcontextplugin.so
7f9a5565e000-7f9a55660000 r-xp 00000000 fc:01 1969865                    /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
7f9a55660000-7f9a55661000 r--p 00001000 fc:01 1969865                    /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
7f9a55661000-7f9a55662000 rw-p 00002000 fc:01 1969865                    /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so
7f9a5566f000-7f9a55670000 rw-p 00000000 00:00 0
7f9a55670000-7f9a55671000 r--p 00000000 fc:01 3540920                    /usr/share/locale-langpack/en_CA/LC_MESSAGES/pulseaudio.mo
7f9a55671000-7f9a55672000 r--p 00025000 fc:01 31748878                   /lib/x86_64-linux-gnu/ld-2.23.so
7f9a55672000-7f9a55673000 rw-p 00026000 fc:01 31748878                   /lib/x86_64-linux-gnu/ld-2.23.so
7f9a55673000-7f9a55674000 rw-p 00000000 00:00 0
7ffc23597000-7ffc235b8000 rw-p 00000000 00:00 0                          [stack]
7ffc235ea000-7ffc235ed000 r--p 00000000 00:00 0                          [vvar]
7ffc235ed000-7ffc235ef000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
```

Occurs even with no one else in the group, no audio or video call active. I can dig into this with gdb tonight. Deserves a hotfix of 1.14.0 IMO.

### PR DESCRIPTION
**Pull request by anthonybilinski**
Fix #5004

---
This change is [Reviewable](https://reviewable.io/reviews/qtox/qtox/5005)

### CODE REVIEW

File: src/widget/widget.cpp [hunk 1]
```diff
@@ -1857,12 +1862,7 @@ void Widget::removeGroup(Group* g, bool fake)
     contactListWidget->removeGroupWidget(widget);
 
     groupWidgets.remove(groupId);
-    delete widget;
```
Comment (anthonybilinski) [inline src/widget/widget.cpp]: this was causing double free with groupWidgets.remove

File: src/widget/widget.cpp [hunk 2]
```diff
@@ -1857,12 +1862,7 @@ void Widget::removeGroup(Group* g, bool fake)
...
-
-    auto chatForm = groupChatForms[groupId];
     groupChatForms.remove(groupId);
-    delete chatForm;
```
Comment (anthonybilinski) [inline src/widget/widget.cpp]: this did not by itself, but I don't see how it's different from the case above.

File: src/widget/widget.cpp (hunk 1 above)
Comment (Diadlo) [reply src/widget/widget.cpp]: I can't find any information that `QMap::remove` free memory for the second component

Comment (anthonybilinski) [reply src/widget/widget.cpp]: For my implementation at least:
```
template <class Key, class T>
Q_OUTOFLINE_TEMPLATE int QMap<Key, T>::remove(const Key &akey)
{
    detach();
    int n = 0;
    while (Node *node = d->findNode(akey)) {
        d->deleteNode(node);
        ++n;
    }
    return n;
}
```
and deleteNode:
```
template <class Key, class T>
void QMapData<Key, T>::deleteNode(QMapNode<Key, T> *z)
{
    QMapNodeBase::callDestructorIfNecessary(z->key);
    QMapNodeBase::callDestructorIfNecessary(z->value);
    freeNodeAndRebalance(z);
}
```
I agree it doesn't mention in the docs :(
There's also this stack overflow question: https://stackoverflow.com/questions/11689465/how-to-remove-values-from-a-qmap which indicates they're similar except regarding iterator incrementing etc.

Comment (Diadlo) [reply src/widget/widget.cpp]: ~It's very strange. No sure, but since deleting by `remove` is not mentioned in docs, I suppose to use `find` + `erase`. What do you think?~

Comment (Diadlo) [reply src/widget/widget.cpp]: It call destructor only for complex types: https://code.woboq.org/qt5/qtbase/src/corelib/tools/qmap.h.html#102
But pointer declared as not complex https://code.woboq.org/qt5/qtbase/src/corelib/global/qtypeinfo.h.html#98

I.e. it calls destructor only for cases like this: `QMap<int, MyCall> map;`

Comment (anthonybilinski) [reply src/widget/widget.cpp]: Good evidence, you're right. The issue isn't the map, it's FriendListWidget::removeGroupWidget which deletes the widget, meaning this diff is still valid to prevent the double free, but the second one is a leak.

Comment (Diadlo) [reply src/widget/widget.cpp]: So `delete chatForm` is invalid, right?

AFAIK `Widget::groupWidgets` contains widgets not only from `FriendListWidget`. So removing in `FriendListWidget` but not in `Widget` will produce errors and memleaks.
We should store `GroupWidget`s and `FriendWidget`s ONLY IN `FriendListWidget` or at least in few similar classes. But it requres a lot of work. For now I sugger remove (or comment) `deleteLater` call from `FriendListWidget::removeGroupWidget` and add `TODO`. 

Or create this classes and move maps from `Widget` to it :)

Comment (anthonybilinski) [reply src/widget/widget.cpp]: No I think the `delete chatForm` is still valid. `delete widget` is only invalid because the same widget is passed into `removeGroupWidget` which deletes it, but nothing similar happens to `GroupChatForm`, it's only removed from the map, so it does need to be manually deleted`. I think.

>So removing in FriendListWidget but not in Widget will produce errors and memleaks

We call `FriendListWidget->removeGroupWidget` on every widget we get from `Widget::groupWidgets` in `Widget::removeGroup` so I think we FriendListWidget must always contain the same Widget.

>We should store GroupWidgets and FriendWidgets ONLY IN FriendListWidget or at least in few similar classes. But it requres a lot of work. For now I sugger remove (or comment) deleteLater call from FriendListWidget::removeGroupWidget and add TODO.
>Or create this classes and move maps from Widget to it :)

I agree, but I'm not very familiar with the area or Widgets/Qt in general, so I want to keep changes minimal for a 1.14 patch to prevent the 100% crash on group leave.

**Comment by anthonybilinski** [comment]
@Diadlo not to rush you, but I want to make 1.14.1 once this is in and I saw you comment on another PR :P. If you're unconvinced by this fix, I'm on Tox now if you want to discuss quicker.

**Comment by Diadlo** [comment]
@anthonybilinski  I'm busy now. Just wanted to test it before LGTM, but haven't time yet. Just not sure, how `deleteLater` will work with signals

**Comment by Diadlo** [comment]
Code :lgtm_strong:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/qtox/qtox/5005#-:-L7i369ZBe8IOs9Lm24A:bnu8ip0)*
