### PR TITLE
fix(profile): Fix for importing profile using Nautilus file manager

### LINKED ISSUE #3436: Profile Import File Picker Initialization Causes Freeze
##### Brief Description

OS: Arch Linux 64bit XFCE
qTox version: Compiled from latest commit (v1.4.0-133-g76239aa)
Commit hash:  684835de1b3a26aac83d1fa99f2bb5a78eab411e
toxcore:  0.0.0
Qt: 5.6.0
Hardware:  Intel, Nvidia
Reproducible: Always
##### Steps to reproduce
1. Open qTox
2. Be not signed in, click on `Import` button
3. Program freezes
##### Observed Behavior

Clicking Import causes the program to freeze with the only solution being to force quit.
##### Expected Behavior

A file picker view to appear.
##### Additional Info

Console output:

```
[04:38:38.358] src/persistence/settings.cpp:121 : Debug: "Loading settings from ~/.config/tox/qtox.ini"
[04:38:38.358] src/ipc.cpp:46 : Debug: Our global IPC ID is  XXXXXXXXXXXXXXXXXXXXX
[04:38:38.358] src/ipc.cpp:64 : Debug: Attaching to the global shared memory
[04:38:38.358] src/ipc.cpp:256 : Debug: Previous owner timed out, taking ownership 8501443004154864147 -> 6814275783135573523
[04:38:38.358] src/main.cpp:200 : Debug: built on:  01:37:04 Jun 25 2016 ( 1466843823 )
[04:38:38.358] src/main.cpp:201 : Debug: commit:  684835de1b3a26aac83d1fa99f2bb5a78eab411e 
[04:38:38.358] src/nexus.cpp:71 : Debug: Starting up
(qtox:13336): GLib-GObject-WARNING **: cannot register existing type 'GdkWindow'
(qtox:13336): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed
(qtox:13336): Gdk-CRITICAL **: gdk_window_ensure_native: assertion 'GDK_IS_WINDOW (window)' failed
```

Did not see any recent information in the log file.

File pickers across all other applications work as expected.

### LINKED ISSUE #3443: qTox crashes when I attempt to transfer a file
qTox crashes when I attempt to transfer a file

OS: Arch Linux
qTox version: v1.4.0-206-g8ac47bf
Commit hash:  8ac47bf06b038cd7decf62a114347579488559a7
toxcore:  0.0.0
Qt:  5.7.0
Hardware:  Generic x86 Hardware
Reproducible: Always
##### Steps to reproduce
1. Start qTox.
2. Attempt to send a file to anyone, doesn't matter if that user is actually online or not.
3. qTox completely stops as soon as I press the paperclip button, requiring you to kill the program.
##### Observed Behavior

Attempting to transfer files crashes qTox.
##### Expected Behavior

File transfer has always worked before, although a bit spotty with large files.
##### Additional Info

No .log-file is created, but I've ran qTox in terminal and saved the terminal output.

[user@sodor ~]$ qtox

(qtox:3212): Gtk-WARNING **: Unable to locate theme engine in module_path: "thinice",

(qtox:3212): Gtk-WARNING **: Unable to locate theme engine in module_path: "mist",
[16:56:36.796] ../src/persistence/settings.cpp:121 : Debug: "Loading settings from /home/user/.config/tox/qtox.ini"
[16:56:36.797] ../src/ipc.cpp:46 : Debug: Our global IPC ID is  16282886912791940011
[16:56:36.797] ../src/ipc.cpp:64 : Debug: Attaching to the global shared memory
[16:56:36.797] ../src/ipc.cpp:256 : Debug: Previous owner timed out, taking ownership 964980879109983768 -> 16282886912791940011
[16:56:36.797] ../src/main.cpp:200 : Debug: built on:  01:05:32 Jun 26 2016 ( 1466895915 )
[16:56:36.797] ../src/main.cpp:201 : Debug: commit:  8ac47bf06b038cd7decf62a114347579488559a7 

[16:56:36.847] ../src/persistence/profile.cpp:86 : Debug: Loading tox save  "/home/user/.config/tox/amitari.tox"
[16:56:36.847] ../src/persistence/settings.cpp:378 : Debug: "Saving global settings at /home/user/.config/tox/qtox.ini"
[16:56:36.892] ../src/persistence/settings.cpp:296 : Debug: Loading personal settings from "/home/user/.config/tox/amitari.ini"
[16:56:36.893] ../src/nexus.cpp:71 : Debug: Starting up
[16:56:37.592] ../src/core/core.cpp:232 : Debug: Loading user profile
[16:56:37.593] ../src/persistence/profile.cpp:243 : Debug: Loading tox save  "/home/user/.config/tox/amitari.tox"
[16:56:37.593] ../src/core/core.cpp:128 : Debug: Core starting with IPv6 enabled
[16:56:39.519] ../src/widget/systemtrayicon.cpp:90 : Debug: Using the Qt backend
[16:56:40.859] ../src/core/core.cpp:403 : Debug: "Connecting to 198.46.138.44:33445 (nurupo)"
[16:56:40.859] ../src/core/core.cpp:403 : Debug: "Connecting to 178.62.250.138:33445 (Impyy)"
[16:56:45.360] ../src/core/core.cpp:403 : Debug: "Connecting to 130.133.110.14:33445 (Manolis)"
[16:56:45.360] ../src/core/core.cpp:403 : Debug: "Connecting to 104.167.101.29:33445 (noisykeyboard)"
[16:56:49.324] ../src/core/core.cpp:370 : Debug: Connected to the DHT
[16:56:49.324] ../src/persistence/profile.cpp:308 : Debug: Saving tox save to  "/home/user/.config/tox/amitari.tox"

(qtox:3212): GLib-GObject-WARNING **: cannot register existing type 'GdkWindow'

(qtox:3212): GLib-CRITICAL **: g_once_init_leave: assertion 'result != 0' failed

(qtox:3212): Gdk-CRITICAL **: gdk_window_ensure_native: assertion 'GDK_IS_WINDOW (window)' failed
^C
[user@sodor ~]$

### PR DESCRIPTION
**Pull request by anoadragon453**
Importing a profile using Nautilus as the default file manager, which many users use, was causing a hang in Qt's  method. Setting Qt to use it's own file manager in this circumstance fixes the issue. Closes #3436, closes #3443.

### CODE REVIEW

**Comment by Diadlo** [comment]
Please, check profile avatar import
[src/widget/form/profileform.cpp:266](https://github.com/tux3/qTox/blob/master/src/widget/form/profileform.cpp#L266)

**Comment by anoadragon453** [comment]
As I do not experience the crash outside of the Import window, I am not able to test whether this change will fix it, but it will at least keep file dialogs consistent. 

Perhaps @Amitari can chime in on the next commit?

**Comment by ghost** [comment]
I'll try the next version, anoadragon453.

File: src/widget/form/chatform.cpp [hunk 1]
```diff
@@ -185,8 +185,12 @@ void ChatForm::onTextEditChanged()
...
 void ChatForm::onAttachClicked()
 {
-    QStringList paths = QFileDialog::getOpenFileNames(this,
-                                                      tr("Send a file"));
+    QStringList paths = QFileDialog::getOpenFileNames ( this,
+                                                      tr("Send a file"),
+                                                      QDir::homePath(),
+                                                      0,
+                                                      0,
+                                                      QFileDialog::DontUseNativeDialog );
```
Comment (zetok) [inline src/widget/form/chatform.cpp]: Won't that cause regression on windows, osx and KDE5, since they use native dialogs?

Comment (Diadlo) [inline src/widget/form/chatform.cpp]: Tested on KDE5. Alright, but it seems, that I have some problems with themes

**Comment by Diadlo** [comment]
Could you try `QFileDialog::getOpenFileName` without last (`QFileDialog::DontUseNativeDialog`) argument? It will still crash?

File: src/widget/form/chatform.cpp (hunk 1 above)
Comment (anoadragon453) [inline src/widget/form/chatform.cpp]: If someone can provide a Windows build of this branch then I can test it on Windows 8.1.

My experience with getting build tools working on Windows has been less than ideal.

**Comment by anoadragon453** [comment]
@Diadlo The `QFileDialog::DontUseNativeDialog` is what prevents the crash. Perhaps one could use a try/catch statement to only use the Internet File Dialog as a fallback?

**Comment by anoadragon453** [comment]
Unforuntealy this bug does not throw a C++ exception of any kind, and simply running the statement without `QFileDialog::DontUseNativeDialog` still freezes the program. I'm not really sure how to check if a freeze will occur without actually causing it?

**Comment by antis81** [comment]
@anoadragon453 

> Unforuntealy this bug does not throw a C++ exception of any kind…

Fortunately Qt follows the "no exception" idiom, pointing you directly to the bug. But seriously, the flag is all fine, because the crash is caused by your native system's Gtk libraries (Using Gnome environment?). Btw. the GLib library got updated several times within the last week, which might solve your problem automagically. 

Making Qt using it's own widget rendering for dialogs is actually a sane decision. Though it has consequences for sure, when it comes to theming. It probably won't use the system's theme, but it's own - namely "Fusion".

EDIT: Sorry, misspelled the framework and library name - corrected this to avoid confusion!

File: src/widget/form/chatform.cpp [hunk 2]
```diff
@@ -185,8 +185,12 @@ void ChatForm::onTextEditChanged()
 
 void ChatForm::onAttachClicked()
 {
-    QStringList paths = QFileDialog::getOpenFileNames(this,
-                                                      tr("Send a file"));
+    QStringList paths = QFileDialog::getOpenFileNames ( this,
```
Comment (antis81) [inline src/widget/form/chatform.cpp]: Can you please remove the spaces here (and before the closing brackets?

File: src/widget/form/chatform.cpp (hunk 1 above)
Comment (antis81) [inline src/widget/form/chatform.cpp]: > My experience with getting build tools working on Windows has been less than ideal.

Surprise, surprise… Nevermind me being ultra sarcastic on those topics! I try to keep my mouth shut. :)

File: src/widget/form/chatform.cpp (hunk 2 above)
Comment (anoadragon453) [inline src/widget/form/chatform.cpp]: I saw this style used in a few other places thus I thought it was the accepted style, but I agree it doesn't looks very nice, and will change each occurrence to omit the space.

**Comment by anoadragon453** [comment]
@antis81 Corrected the style issues. On Arch Linux I still suffer from this issue, however I'll look out for it in the future to see if this issue is fixed in newer versions of GTK.

**Comment by anoadragon453** [comment]
Hold up on the merge, it seems the program still freezes upon asking where to save the QR code of the Tox ID, as well as when exporting one's Tox profile. It oddly enough works fine when asking the user the default directory to save files to.

File: src/widget/form/chatform.cpp [hunk 3]
```diff
@@ -185,8 +185,12 @@ void ChatForm::onTextEditChanged()
 
 void ChatForm::onAttachClicked()
 {
-    QStringList paths = QFileDialog::getOpenFileNames(this,
-                                                      tr("Send a file"));
+    QStringList paths = QFileDialog::getOpenFileNames (this,
```
Comment (antis81) [inline src/widget/form/chatform.cpp]: Thanks! Forgot one space here… :)

**Comment by anoadragon453** [comment]
All spaces should have been eradicated :) 

Edit: Moving on to the other freezes now.

**Comment by anoadragon453** [comment]
Turns out `QFileDialog::getSaveFileName` and `QFileDialog::getExistingDirectory` were troublemakers as well. Those have been patched up as well now.

**Comment by antis81** [comment]
Now that looks nice! Are we ready to merge?

**Comment by anoadragon453** [comment]
Couldn't find any more crashes myself, so a go ahead from me!

**Comment by mcd1992** [comment]
Was having the same issues on Arch with XFCE. Your nautilus-fix branch works just fine for me.

**Comment by anoadragon453** [comment]
Glad to hear it Aaron.

On 07/03/2016 02:13 PM, Aaron (Moved to Gitlab) wrote:

> Was having the same issues on Arch with XFCE. Your nautilus-fix branch
> works just fine for me.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> https://github.com/tux3/qTox/pull/3447#issuecomment-230175715, or mute
> the thread
> https://github.com/notifications/unsubscribe/ABR7mNCW1V53NfZMW5CjAhjN7E9vx3D_ks5qSCXmgaJpZM4I_wFn.

## 

Andrew

PGP Fingerprint:
C5D9 804C 6FA0 AA57 7441 0641 174B EAB0 09FD 176D
